woowacourse/java-http

README.md, app/build.gradle, app/src/main/java/nextstep/jwp/RequestHandler.java, app/src/main/java/nextstep/jwp/UserService.java, app/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, app/src/main/resources/static/login.html, app/src/test/java/nextstep/jwp/RequestHandlerTest.java, app/src/test/java/nextstep/learning/http/FileTest.java, app/src/test/java/nextstep/learning/http/IOStreamTest.java
독특한 미션이었네요
꺠끗한 코드를 만들기가 상당히 어려운 미션이었던 것 같아요.
특히 책임 분리나 메소드 형태를 볼 때 팩토리 패턴과 같은 디자인을 도입하면 더 좋을 것 같았는데
그 부분은 리펙토링 과정에서 처리하기로 했습니다.
잘 부탁드려요
=> [HTTP 서버 구현하기 - 1단계] 마갸(정찬영) 미션 제출합니다.

app/src/main/java/nextstep/jwp/RequestHandler.java, app/src/main/java/nextstep/jwp/controller/LoginController.java, app/src/main/java/nextstep/jwp/core/HandlerMapping.java, app/src/main/java/nextstep/jwp/db/HttpSessions.java, app/src/main/java/nextstep/jwp/model/User.java, app/src/main/java/nextstep/jwp/web/Cookie.java, app/src/main/java/nextstep/jwp/web/HttpRequest.java, app/src/main/java/nextstep/jwp/web/HttpRequestParser.java, app/src/main/java/nextstep/jwp/web/HttpResponse.java, app/src/main/java/nextstep/jwp/web/HttpSession.java, app/src/main/java/nextstep/jwp/web/HttpVersion.java, app/src/main/java/nextstep/jwp/web/RequestLine.java, app/src/main/java/nextstep/jwp/web/exception/NoSuchHttpVersionException.java, app/src/test/java/nextstep/jwp/controller/LoginControllerTest.java, app/src/test/java/nextstep/jwp/db/HttpSessionsTest.java, app/src/test/java/nextstep/jwp/web/CookieTest.java, app/src/test/java/nextstep/jwp/web/HttpRequestParserTest.java, app/src/test/java/nextstep/jwp/web/HttpSessionTest.java
안녕하세요 마갸! 이른 아침부터 빠르게 확인하고 머지해주신 덕에 2, 3단계를 오늘 제출할 수 있게 되었네요!
2단계는 1단계를 진행하면서 이미 해버려서 ㅎ.ㅎ... 쿠키와 세션 기능을 구현해보았습니다.
가차없는 피드백 부탁드립니다. :)
=> [HTTP 서버 구현하기 - 2, 3단계] 김김(김기문) 미션 제출합니다.

README.md, app/src/main/java/nextstep/jwp/WebServer.java, app/src/main/java/nextstep/jwp/dispatcher/handler/HttpHandler.java, app/src/main/java/nextstep/jwp/http/HttpRequest.java, app/src/main/java/nextstep/jwp/http/HttpResponse.java, app/src/main/java/nextstep/jwp/http/HttpResponseImpl.java, app/src/main/java/nextstep/jwp/http/message/HttpCookie.java, app/src/main/java/nextstep/jwp/http/message/HttpCookies.java, app/src/main/java/nextstep/jwp/http/parser/HttpParser.java, app/src/main/java/nextstep/jwp/http/session/HttpSession.java, app/src/main/java/nextstep/jwp/http/session/HttpSessions.java, app/src/main/java/nextstep/project/presentation/LoginController.java, app/src/main/resources/static/login.html, app/src/test/java/nextstep/jwp/RequestHandlerTest.java, app/src/test/java/nextstep/jwp/http/HttpResponseTest.java, app/src/test/java/nextstep/jwp/http/message/HttpCookieTest.java, app/src/test/java/nextstep/jwp/http/message/HttpCookiesTest.java, app/src/test/java/nextstep/jwp/http/parser/HttpParserTest.java
1단계때 리팩토링 부분은 구현하여서, 이번 단계에선 쿠키와 세션을 적용해보았어요!
Request에서 `getSession()`을 통해 해당 요청에 대한 세션을 가지고 올 수 있게 하였습니다!
또한, Response에 `addCookie()`를 통해 쿠키를 설정해줄 수 있게 하였습니다.
<br>
이를 통해 요구사항에 있는 `/login`에 접속했을 때 세션을 통해 로그인 상태면 `index.html`로 리다이렉트하도록 해두었습니다!
<br>
> 사실 리팩토링과 테스트하고 싶은 부분이 많지만ㅠ 다른 할 일로 인해 모두 못한 점이 아쉽네요.. 피드백 받고 리팩토링해보겠습니다ㅎㅎ
<br>
=> [HTTP 서버 구현하기 - 2, 3단계] 마크(김병화) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/AuthController.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/QueryParams.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
=> [톰캣 구현하기 - 1단계] 소주캉(강승주) 미션 제출합니다.

README.md, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/LoginFailureException.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeader.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaderFactory.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestHeaders.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpResponseTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestHeaderFactoryTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestHeaderTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/RequestHeadersTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 정✋🏻 
코드 `쓰레기` 같을 수 있지만 잘 부탁드립니다🙏🏻 
고생이 많으십니다. 많은 지적 부탁드려요.
=> [톰캣 구현하기 - 1단계] 잉(유영우) 미션 제출합니다.

README.md, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 라쿤!
1단계까지만 하는 줄 모르고 2단계의 1번까지 구현해버렸어요ㅠㅠ 양해를 부탁드립니다🙇🏻‍♀️
코드를 적고 나니 너무 더러워 라쿤이 이해하실 수 있을지 모르겠어요..
도움이 되실까 하는 마음에 간단한 각 함수의 설명 함께 적어봅니다.
- process()
- 요청을 받아 HttpRequest로 파싱
- uri 확인 후 각 uri에 맞는 메서드 호출을 통해 HttpResponse 연산
- HttpResponse를 outputStream으로 내보냄
- main()
- 200 OK와 함께 Hello World 반환
- getResource()
- 200 OK와 함께 파일을 읽어 내용 반환
- login()
- 쿼리 스트링이 존재하지 않는 경우 
- 200 OK와 함께 로그인 페이지 반환
- 쿼리스트링이 존재하는 경우 
- 쿼리 스트링 파싱하여 account, password 알아냄
- 비밀번호 일치 여부에 따라 Location 헤더필드에 알맞은 uri를 추가함으로써 redirect
- parseQueryString()
- 쿼리 스트링을 파싱하여 Map 형태로 반환
- readFile()
- 파일을 읽어 String 형태로 반환
요청과 응답을 객체로 만든 것
=> [톰캣 구현하기 - 1단계] 아리(양유림) 미션 제출합니다.

tomcat/build.gradle, tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, tomcat/src/main/java/org/apache/coyote/http11/ArgumentResolver.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpMessageSupporter.java, tomcat/src/main/java/org/apache/coyote/http11/LoginFilter.java, tomcat/src/main/java/org/apache/coyote/http11/PathParser.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/ArgumentResolverTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/HttpMessageSupporterTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/PathParserTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 코린 이렇게 만나게 돼서 영광입니다.
많이 부족하지만 편하게 봐주세요!!
=> [톰캣 구현하기 - 1단계] 칙촉(안영윤) 미션 제출합니다. 

tomcat/src/main/java/nextstep/jwp/exception/LoginFailedException.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
잘 부탁드립니다!!! 감사합니다!!!! 궁금하신 내용 있으시면 언제든 dm주세요!!
=> [톰캣 구현하기 - 1단계] 조시(조현근) 미션 제출합니다.

README.md, tomcat/src/main/java/http/ContentType.java, tomcat/src/main/java/org/apache/coyote/http/ContentType.java, tomcat/src/main/java/org/apache/coyote/http/HttpHeader.java, tomcat/src/main/java/org/apache/coyote/http/HttpVersion.java, tomcat/src/main/java/org/apache/coyote/http/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http/request/HttpRequestLine.java, tomcat/src/main/java/org/apache/coyote/http/request/QueryParams.java, tomcat/src/main/java/org/apache/coyote/http/request/RequestMethod.java, tomcat/src/main/java/org/apache/coyote/http/request/RequestPath.java, tomcat/src/main/java/org/apache/coyote/http/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http/response/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 후디!
이번 미션 진행하면서 감기몸살에 걸려서 많이 집중하지 못한거 같네요
3단계때 리팩토링이 있어서 일단은 pr 제출합니다.
=> [톰캣 구현하기 - 1단계] 승팡(김승래) 미션 제출합니다.

tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpContent.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java, tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
조시 반갑습니다~ 이번 1단계 미션에 대해 리뷰 요청 드립니다!🥕
최대한 역할을 나누어서 개발을 하고 싶었는데, 문자열 파싱의 책임이 모호하게 느껴져서 역할 분리가 어려웠습니다🥺
리뷰 잘 부탁드립니다🥹
=> [톰캣 구현하기 - 1단계] 라쿤(이병훈) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java, tomcat/src/main/java/nextstep/jwp/http/ContentType.java, tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java, tomcat/src/main/java/nextstep/jwp/http/QueryParam.java, tomcat/src/main/java/nextstep/jwp/http/QueryParams.java, tomcat/src/main/java/nextstep/jwp/utils/FileUtils.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/nextstep/jwp/handler/LoginHandlerTest.java, tomcat/src/test/java/nextstep/jwp/http/ContentTypeTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpRequestTest.java, tomcat/src/test/java/nextstep/jwp/http/QueryParamTest.java, tomcat/src/test/java/nextstep/jwp/http/QueryParamsTest.java, tomcat/src/test/java/nextstep/jwp/utils/FileUtilsTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
디우 안녕하세요. 오랜만에 미션이라 재미있었습니다. ㅎㅎ
1단계 기능 구현을 완료하였습니다.
리팩터링과 예외 처리 관련하여 자유롭게 의견 주셔도 됩니다!
구현한 기능 목록
=> [톰캣 구현하기 - 1단계] 레오(남궁현) 미션 제출합니다.

tomcat/build.gradle, tomcat/src/main/java/nextstep/jwp/controller/HomeController.java, tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/StaticResourceController.java, tomcat/src/main/java/nextstep/jwp/exception/UnauthorizedException.java, tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/ContentTypeExtractor.java, tomcat/src/main/java/org/apache/coyote/http11/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestConvertor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponseBuilder.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/ContentTypeExtractorTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java, tomcat/src/test/java/support/StubSocket.java
어렵습니다...
어떻게 해야할지... 감이 안잡히네요 ㅠㅠ
=> [톰캣 구현하기 - 1단계] 베루스(정진혁) 미션 제출합니다.

tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/QueryMapper.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/ContentTypeTest.java, tomcat/src/test/java/org/apache/coyote/http11/QueryMapperTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java, tomcat/src/test/java/study/UrlTest.java
안녕하세요 파랑!💙 마루입니다😊
클래스 분리를 어떤 식으로 해야 좋을 지 감이 잘 잡히지 않아서 일단 메서드 분리를 중심으로 리팩터링 하였습니다!
코드를 읽기에 힘든 부분이 있다거나, 개선하면 좋을 것 같은 부분들이 있으면 알려주세요:)
리뷰 감사합니다🙇‍♂️
=> [톰캣 구현하기 - 1단계] 마루(송채원) 미션 제출합니다.

tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 엘리!
저 짱군데요, 구현은 했지만 코드가 지저분하네요...
리팩토링 하겠습니다..!
=> [톰캣 구현하기 - 1단계] 짱구(신승철) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/application/LoginService.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestUri.java, tomcat/src/main/java/org/apache/coyote/http11/StartLine.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 봄🌱 아서입니다!
프로젝트하랴, 미션하랴, 실습하랴 레벨4 정말 정신이 없네요...ㅠㅠ
그래도 오랜만에 미션하니까 재미있었습니다:)
코드가 아직 엉망인 것 같은데 3단계 때 리팩토링이 있길래 우선 제출합니다!
봄이 생각하기에 고민할만한 사항이거나 이상하다고 느껴지시면 편하게 전부 지적해주세요.
=> [톰캣 구현하기 - 1단계] 아서(김현태) 미션 제출합니다.

tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpRequestTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 이프!
제가 코로나에 걸려서 미션에 시간을 쏟지 못했네요..ㅠㅠ
1단계를 우선 구현 했는데, 무슨 문제인지 html을 파일을 가져오면 인코딩이 안되는 문제가 생겨서 테스트가 통과하지 않네요 ㅠ.ㅠ
시간 때문에 PR은 내는데 제가 더 찾아보겠습니다!
=> [톰캣 구현하기 - 1단계] 주디(윤주리) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/exception/UserNotFoundException.java, tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
=> [톰캣 구현하기 - 1단계] 슬로(이한울) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
칙촉 안녕하세요 : ) 
구조나 설계적으로 아직 리팩토링이 많이 필요한 상태입니다! 리뷰 반영하면서 구조 리팩토링하고 테스트 추가하도록 하겠습니다!
잘 부탁드려요🙇‍♀️
=> [톰캣 구현하기 - 1단계] 봄(장보미) 미션 제출합니다.

README.md, tomcat/src/main/java/org/apache/coyote/http11/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/QueryStringParser.java, tomcat/src/main/java/org/apache/coyote/http11/ViewResolver.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 포키! 
이렇게 또 만나게 되서 반갑습니다!!
미션 진행하는데 오래 걸려서 설계에 신경을 쓰지 못했네요..
현재로서는 1단계 요구사항만 완료한 상황입니다! 
리팩토링을 하면서 리뷰 기다리고 있겠습니다!
=> [톰캣 구현하기 - 1단계] 쿤(홍동건) 미션 제출합니다.

README.md, tomcat/build.gradle, tomcat/src/main/java/nextstep/jwp/exception/AuthenticationException.java, tomcat/src/main/java/nextstep/jwp/exception/ResourceNotFoundException.java, tomcat/src/main/java/nextstep/jwp/exception/UserNotFoundException.java, tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Path.java, tomcat/src/main/java/org/apache/coyote/http11/QueryParameters.java, tomcat/src/main/java/org/apache/coyote/http11/ResponseProcessor.java, tomcat/src/main/java/org/apache/coyote/http11/StartLine.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/ContentTypeTest.java, tomcat/src/test/java/org/apache/coyote/http11/ControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/PathTest.java, tomcat/src/test/java/org/apache/coyote/http11/QueryParametersTest.java, tomcat/src/test/java/org/apache/coyote/http11/ResponseProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java, tomcat/src/test/resources/static/nextstep.txt
안녕하세요 리차드 🎸 
항상 웃으면서 인사해주셔서 내적 친밀감이 많이 쌓였는데, 이렇게 리뷰를 부탁드리게 되어 영광입니다!
1단계만 구현하여 리뷰 요청을 보냅니다!
많은 지적 부탁드리겠습니다. 감사합니다 🙇
=> [톰캣 구현하기 - 1단계] 에덴(김성산) 미션 제출합니다.

tomcat/src/main/java/org/apache/coyote/http11/Handler.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestStartLine.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestStartLineContents.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 베루스!
시간에 쫓겨서 하다가 생각치 못한 오류를 맛봐서 아직 요구사항도 다 못하였네요ㅜㅜ죄송합니다.
추가 요구사항까지 다 반영한 후에 다시 리뷰요청을 드리겠습니다!
다시 한 번 죄송합니다...
=> [톰캣 구현하기 - 1단계] 아스피(신동석) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/handler/HttpRequestHandler.java, tomcat/src/main/java/nextstep/jwp/handler/LoginRequestHandler.java, tomcat/src/main/java/nextstep/jwp/handler/RegisterRequestHandler.java, tomcat/src/main/java/nextstep/jwp/http/ContentType.java, tomcat/src/main/java/nextstep/jwp/http/HttpCookie.java, tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java, tomcat/src/main/java/nextstep/jwp/http/HttpRequestBody.java, tomcat/src/main/java/nextstep/jwp/http/HttpRequestHeaders.java, tomcat/src/main/java/nextstep/jwp/http/HttpResponse.java, tomcat/src/main/java/nextstep/jwp/http/HttpStatus.java, tomcat/src/main/java/nextstep/jwp/http/HttpVersion.java, tomcat/src/main/java/nextstep/jwp/http/Location.java, tomcat/src/main/java/nextstep/jwp/http/Session.java, tomcat/src/main/java/nextstep/jwp/http/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/jwp/http/HttpCookieTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpRequestBodyTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpRequestHeadersTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpRequestTest.java, tomcat/src/test/java/nextstep/jwp/http/LocationTest.java
안녕하세요 더즈 :)
최대한 빠르게 드리고 싶었는데 컨디션이 안좋아서 많이 늦어졌네요 ㅜㅜ
지난번에 비해서 크게 고민한 부분은 없고 http에 대한 공부를 더 하게 되었던 미션인 것 같네요 ㅎㅎ
감사합니다 🙇‍♂️
=> [톰캣 구현하기 - 2단계] 오리(최진영) 미션 제출합니다.

tomcat/build.gradle, tomcat/src/main/java/org/apache/coyote/http/HttpHeader.java, tomcat/src/main/java/org/apache/coyote/http/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http/HttpRequestBody.java, tomcat/src/main/java/org/apache/coyote/http/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http/HttpStatusCode.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Session.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java, tomcat/src/main/java/org/apache/coyote/util/StringParser.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/org/apache/coyote/http/HttpHeaderTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http/HttpRequestTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http/HttpResponseTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/util/StringParserTest.java, tomcat/src/test/java/org/apache/coyote/http/HttpHeaderTest.java, tomcat/src/test/java/org/apache/coyote/util/StringParserTest.java, tomcat/src/test/java/study/FileTest.java, tomcat/src/test/java/study/IOStreamTest.java
안녕하세요 아스피~!!
1단계만 제출인줄 모르고 1, 2단계를 구현해버렸어요.. 🥺
코드가 많이 지저분한데 감이 잘 안 잡히네요 ㅠㅅㅠ
리뷰 잘 부탁합니다 😉
=> [톰캣 구현하기 - 1, 2단계] 릭(나일성) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, tomcat/src/main/java/nextstep/jwp/exception/UserNotFoundException.java, tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java, tomcat/src/main/java/nextstep/jwp/http/ContentType.java, tomcat/src/main/java/nextstep/jwp/http/Cookie.java, tomcat/src/main/java/nextstep/jwp/http/HttpHeaders.java, tomcat/src/main/java/nextstep/jwp/http/HttpMethod.java, tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java, tomcat/src/main/java/nextstep/jwp/http/HttpResponse.java, tomcat/src/main/java/nextstep/jwp/http/QueryParam.java, tomcat/src/main/java/nextstep/jwp/http/QueryParams.java, tomcat/src/main/java/nextstep/jwp/http/StatusCode.java, tomcat/src/main/java/nextstep/jwp/model/User.java, tomcat/src/main/java/nextstep/jwp/utils/FileUtils.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/session/Session.java, tomcat/src/main/java/org/apache/session/SessionManager.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/jwp/handler/LoginHandlerTest.java, tomcat/src/test/java/nextstep/jwp/http/ContentTypeTest.java, tomcat/src/test/java/nextstep/jwp/http/CookieTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpHeadersTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpMethodTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpRequestTest.java, tomcat/src/test/java/nextstep/jwp/http/HttpResponseTest.java, tomcat/src/test/java/nextstep/jwp/http/StatusCodeTest.java, tomcat/src/test/java/nextstep/jwp/utils/FileUtilsTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
디우 안녕하세요! 2단계 구현되었습니다.
- 로그인에 성공하면 상태코드 302를 반환한다.
- Http Method가 Post이고 Content-Type RequestHeader가 `application/x-www-form-urlencoded` 이면 회원가입/로그인을 한다.
- Http Methode가 Get이면 회원가입/로그인 페이지로 이동한다.
- 회원가입 또는 로그인을 하면 JsessionId를 키로 가진 Cookie를 반환한다.
- 회원가입 또는 로그인을 하면 세션을 만들고 JsessionId를 Cookie로 전달한다.
- 로그인 페이지로 접속할 때 JsessionId가 일치하면 index.html을 반환한다.
=> [톰캣 구현하기 - 2단계] 레오(남궁현) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, tomcat/src/main/java/nextstep/jwp/exception/DuplicateUserException.java, tomcat/src/main/java/nextstep/jwp/handler/RequestHandler.java, tomcat/src/main/java/nextstep/jwp/http/common/HttpCookie.java, tomcat/src/main/java/nextstep/jwp/http/common/HttpHeaders.java, tomcat/src/main/java/nextstep/jwp/http/common/HttpStatus.java, tomcat/src/main/java/nextstep/jwp/http/common/Session.java, tomcat/src/main/java/nextstep/jwp/http/common/SessionManager.java, tomcat/src/main/java/nextstep/jwp/http/request/HttpRequest.java, tomcat/src/main/java/nextstep/jwp/http/request/HttpRequestFactory.java, tomcat/src/main/java/nextstep/jwp/http/request/RequestBody.java, tomcat/src/main/java/nextstep/jwp/http/response/HttpResponse.java, tomcat/src/main/java/nextstep/jwp/http/util/FileReader.java, tomcat/src/main/java/nextstep/jwp/presentation/AbstractController.java, tomcat/src/main/java/nextstep/jwp/presentation/DefaultController.java, tomcat/src/main/java/nextstep/jwp/presentation/LoginController.java, tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java, tomcat/src/main/java/nextstep/jwp/presentation/ResourceController.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/jwp/http/factory/HttpRequestFactoryTest.java, tomcat/src/test/java/nextstep/jwp/presentation/DefaultControllerTest.java, tomcat/src/test/java/nextstep/jwp/presentation/LoginControllerTest.java, tomcat/src/test/java/nextstep/jwp/presentation/RegisterControllerTest.java, tomcat/src/test/java/nextstep/jwp/presentation/ResourceControllerTest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 후니 💪 
지난 PR에서 3단계 조금씩 진행했어서 2, 3단계를 같이 제출합니다. 아직 단위 테스트가 작성되어 있지 않는데요.. 계속해서 HttpXXX 구조를 변경하다보니 시간이 많이 지체되어서 일단 통합테스트만 작성했습니다 😅
이번에도 피드백 잘 부탁드릴게요~~
=> [톰캣 구현하기 - 2, 3단계] 루키(최지훈) 미션 제출합니다. 

tomcat/src/main/java/nextstep/jwp/http/common/ContentType.java, tomcat/src/main/java/nextstep/jwp/http/request/HttpRequest.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java
후니~~ 간단하게 Thread Pool만 적용시켜 보았습니다. 이번 기회에 Thread 관련해서 공부할 수 있어서 좋았네요 😁
마지막 리뷰도 잘 부탁드릴게요 🥳
=> [톰캣 구현하기 - 4단계] 루키(최지훈) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/config/WebConfig.java, tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java, tomcat/src/main/java/nextstep/jwp/controller/ErrorHandler.java, tomcat/src/main/java/nextstep/jwp/controller/HelloController.java, tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/nextstep/jwp/controller/ResourceController.java, tomcat/src/main/java/nextstep/jwp/controller/View.java, tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, tomcat/src/main/java/nextstep/jwp/exception/WrongInputException.java, tomcat/src/main/java/nextstep/jwp/model/User.java, tomcat/src/main/java/nextstep/jwp/service/UserService.java, tomcat/src/main/java/nextstep/jwp/util/ResourceLoader.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/ExceptionHandler.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestHandler.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/QueryParams.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/body/RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/header/Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/requestline/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/requestline/RequestUri.java, tomcat/src/main/java/org/apache/coyote/http11/message/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/message/response/header/Headers.java, tomcat/src/test/java/nextstep/jwp/service/UserServiceTest.java
안녕하세요 제로~! 3단계에서 달아주신 리뷰 반영하며 refactoring 약간 진행한 뒤, 요구사항 구현했습니다.
머지까지 기간이 좀 남은 만큼 의견 편하게 남겨주시면 열심히 반영해볼게요.
추석 연휴 잘 보내세욥~! 🎉
=> [톰캣 구현하기 - 4단계] 포키(권예진) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java
루키! 4단계는 비교적 간단해서 빨리 구현해보았어요!!
4단계말고 추가적인 피드백 주셔도 좋을 것 같아요! 마지막 피드백 잘 부탁드립니다!
추석 잘보내세요😘
=> [톰캣 구현하기 - 4단계] 크리스(공병주) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/controller/LoginServlet.java, tomcat/src/main/java/org/apache/catalina/Session.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Headers.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/StatusLine.java, tomcat/src/main/java/org/apache/servlet/HttpServlet.java, tomcat/src/main/java/org/apache/servlet/ResourceServlet.java, tomcat/src/main/java/org/apache/servlet/ServletContainer.java, tomcat/src/test/java/org/apache/coyote/http11/HttpCookieTest.java
안녕하세요 앤지! 매트입니다 😃
**🚀 2단계 - 로그인 구현하기**, **🚀 3단계 - 리팩터링** 미션 잘 부탁드립니다 🙏
이전 PR에 남겨주신 리뷰에 개선사항 남겨두었습니다! [https://github.com/woowacourse/jwp-dashboard-http/pull/125](https://github.com/woowacourse/jwp-dashboard-http/pull/125)
추가적으로 현재 2, 3 단계 모두 완료한 상태입니다. 이번 리뷰도 잘 부탁드립니다! 감사합니다 🙇‍♂️
=> [톰캣 구현하기 - 2, 3, 4단계] 매트(최기현) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseLine.java, tomcat/src/main/java/org/apache/coyote/http11/session/Session.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/utils/QueryParamsParser.java, tomcat/src/main/java/org/apache/coyote/http11/utils/RequestMappingHandler.java, tomcat/src/main/resources/static/400.html, tomcat/src/main/resources/static/401.html
안녕하세요 범고래!
구현사항이 많지는 않아 빠르게 리뷰요청 보냅니다.
혹시나 동시성 컬렉션 사용이 필요한데 누락된 부분이 있거나, 지나치게 많이 사용해서 오히려 성능 이슈가 있다고 생각되는 부분이 있다면 피드백 부탁드려요! 그 이외에 컨벤션, 메서드명으로 이상한 부분 있다면 말씀해주세요.
감사합니다!
=> [톰캣 구현하기 - 4단계] 케이(김태현) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/controller/ControllerMapper.java, tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/MainController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/nextstep/jwp/controller/RequestMapping.java, tomcat/src/main/java/nextstep/jwp/controller/ResourceController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestStartLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatus.java, tomcat/src/test/java/nextstep/jwp/controller/HttpRequestGenerator.java, tomcat/src/test/java/nextstep/jwp/controller/LoginControllerTest.java, tomcat/src/test/java/nextstep/jwp/controller/MainControllerTest.java, tomcat/src/test/java/nextstep/jwp/controller/RegisterControllerTest.java, tomcat/src/test/java/nextstep/jwp/controller/RequestMappingTest.java, tomcat/src/test/java/nextstep/jwp/controller/ResourceControllerTest.java
안녕하세요 라쿤! 아리입니다. ⭐️
드디어 대망의 마지막 단계네요...ㅎ
3단계의 경우 요구사항에 맞춰 네이밍 변경을 진행했습니다.
4단계의 경우 작성한 코드는 몇줄 없지만 새롭게 알게된 지식이 많아 README.md에 정리해두었으니 참고 부탁드립니다!
추가적으로 요청이 들어올 때 마다 Controller 인스턴스가 생성되는 것이 좋아보이지 않아 싱글턴 패턴을 적용하도록 리팩토링 했습니다.
마지막까지 잘 부탁드립니다🙇🏻‍♀️
=> [톰캣 구현하기 - 3, 4단계] 아리(양유림) 미션 제출합니다.

README.md, tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java, tomcat/src/main/java/nextstep/jwp/controller/Controller.java, tomcat/src/main/java/nextstep/jwp/controller/HelloWorldController.java, tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/nextstep/jwp/controller/RequestMapping.java, tomcat/src/main/java/nextstep/jwp/controller/StaticFileController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
안녕하세요, 레오! 생각보다 4단계의 볼륨이 작아서 3단계와 함께 진행했습니다!
시간에 쫒겨 다소 급하게 마무리한 것 같아서 아쉽네요 🥲
리뷰 남겨주시면 열심히 반영해보겠습니다! 마지막도 잘 부탁드려요 🥹
=> [톰캣 구현하기 - 3, 4단계] 후디(조동현) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/file/ResourceLoader.java, tomcat/src/main/java/org/apache/coyote/http11/support/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/web/response/HttpResponse.java, tomcat/src/test/java/org/apache/coyote/http11/support/session/SessionManagerTest.java
안녕하세요 크리스!
4단계까지 끝내고 리뷰 요청 보냅니다~!
4단계 구현은 쉬웠는데, 테스트를 어떤 식으로 해야할 지 모르겠네욤...
혹시 크리스는 테스트를 어떻게 하셨는지 공유해주시면 감사하겠습니다~!
그럼 즐거운 추석보내세요~~!!
=> [톰캣 구현하기 - 4단계] 썬(윤선용) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/servlets/AbstractController.java, tomcat/src/main/java/org/apache/coyote/http11/ResourceLocator.java, tomcat/src/main/java/org/apache/coyote/http11/general/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/general/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/test/java/nextstep/jwp/controller/LoginControllerTest.java, tomcat/src/test/java/org/apache/catalina/servlets/AbstractControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestTest.java
안녕하세요 레넌~ 3단계 리뷰를 아직 못받았지만 오늘까지 PR 제출이라 우선 구현하여 제출합니다. 2, 3단계 리뷰도 여기다가 하셔도 될 것 같아요
=> [톰캣 구현하기 - 4단계] 어썸오(정수현) 미션 제출합니다.

tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/PathProcessor.java, tomcat/src/main/java/org/apache/request/HttpBody.java, tomcat/src/main/java/org/apache/request/HttpHeaders.java, tomcat/src/main/java/org/apache/request/HttpLine.java, tomcat/src/main/java/org/apache/request/HttpRequest.java, tomcat/src/main/java/org/apache/response/HttpResponse.java
안녕하세요 리오,
1단계 미션을 완료하여 PR 요청합니다.
미리 양해를 구하지 못하고 늦게 리뷰를 요청드리는 점,
2단계까지 완료하지 못하고 리뷰를 요청드리는 점을 사과드립니다.
몸이 좋지 않아 지난 주 목요일부터 주말까지 진도를 놓친 탓에,
미션의 존재와 기한을 월요일 오전에서야 알았네요.
최대한 빨리 2단계까지 구현하고 요청드리고 싶었으나,
역량이 부족한 탓에 1단계까지만 구현하고 먼저 요청드립니다.
사정을 막론하고,
미리 공유드리지 못하고 일정과 진도에 어긋난 리뷰를 요청드리는 점,
그로 인해 리뷰를 통한 리오의 학습이 방해된 점에 대해 진심으로 사과드립니다.
대면하여 다시 사과드리겠습니다.
아래에는 구현한 내용에 대한 간단한 설명을 첨부합니다.
- PathProcessor : path에 대한 분기에 따라, content를 작성하여 반환하는 Util 클래스
---
리오가 해당 리뷰요청에 대해 내리실 어떠한 판단이든 존중합니다.
감사합니다.
=> [톰캣 구현하기 - 1단계] 체인저(이우진) 미션 제출합니다.

README.md, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/Session.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java, tomcat/src/main/resources/static/login.html
안녕하세요 루카~~!
1, 2단계까지 구현해봤는데 잘 부탁드립니다🙇‍♂️
3단계가 리팩터링이라고 해서 아직 리팩터링은 진행 안했어요..
그래서 코드가 많이 복잡할 수 있어요.. 하하
다음 단계에서 기가 막히게 리팩터링 해보겠읍니다^^
리뷰 잘 부탁드려요 😎
=> [톰캣 구현하기 1, 2단계] 망고(고재철) 미션 제출합니다.

study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/Session.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java, tomcat/src/main/resources/static/login.html
안녕하세요 오잉~?
시간이 좀 부족하다보니 구현에 초점을 맞추어서 진행했는데요
`Http11Processor`에 if문의 분기문을 아직 처리는 못했는데 3단계때 개선해나가겠습니다
코드가 좀 지저분하지만,, 리뷰 잘부탁드려요
(이해안되는코드가 있으면 편하게 DM주세요)
=> [톰캣 구현하기 1, 2단계] 루쿠(백경환) 미션 제출합니다.

study/src/main/java/cache/com/example/cachecontrol/CacheInterceptor.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/java/cache/com/example/version/ResourceVersion.java, study/src/main/resources/application.yml, study/src/main/resources/templates/resource-versioning.html, study/src/test/java/cache/com/example/GreetingControllerTest.java, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/nextstep/Application.java, tomcat/src/main/java/org/apache/catalina/HttpSession.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestHeader.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 오도!
오랜만에 리뷰어와 리뷰이로라도 만나 반갑네요!
코드에서 냄새가 많이 나는 점 죄송합니다..
추후에 조언 주시는 것을 적극적으로 반영하여 코드 냄새를 제거해 나가도록 하겠습니다.
리뷰 잘 부탁드려요!
=> [톰캣 구현하기 1, 2단계] 매튜(김재연) 미션 제출합니다. 

study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/catalina/session/Session.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestFactory.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestCookie.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/response/ResponseCookie.java, tomcat/src/main/java/org/apache/coyote/http11/response/ResponseHeaders.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 허브!!
드뎌 허브신의 코드리뷰를 받아보는 영광을 누리게 되었는데,,, 미리미리 진행하지 못한 미션때문에 이렇게 다 끝내지도 못하고 늦게 제출하게 되네요ㅠㅜ
구현 상황은 2단계의 로그인까지 구현이 되어있습니다.
쿠키와 세션 부분은 구현을 하려다 보면 더 늦어질 것 같아서...
일단 미션 제출합니다.
미진행된 부분은 리팩터링 하기 전 진행하도록 하겠습니다!
급하게 작업하다보니 예외핸들링이나 코드적으로나 놓치고 지나간 부분들이 너무 많네요...
리팩터링 하며 최대한 반영하고 고쳐보도록 하겠습니다.
=> [톰캣 구현하기 1, 2단계] 필립(양재필) 미션 제출합니다.

study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, tomcat/src/main/java/nextstep/jwp/db/InMemoryUserRepository.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/common/HttpProtocolVersion.java, tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/controller/IndexPageController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeader.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestStartLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpProtocolVersion.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseBody.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseStatusLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/ResponseEntity.java, tomcat/src/main/java/org/apache/coyote/http11/session/HttpCookie.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/LoginTest.java, tomcat/src/test/java/org/apache/coyote/http11/response/ContentTypeTest.java
준팍 안녕하세요!!! 
3단게 리팩터링까지 완료했습니다
요구사항에 써있는 내용을 간결하게 구현하기 위해서 노력했어요🌟
4단계는 조금 학습에 시간이 필요할 것 같아서
우선 3단계부터 리뷰 요청하겠습니당
좋은 하루 되세요〰️
=> [톰캣 구현하기 - 3단계] 깃짱(조은기) 미션 제출합니다.

study/src/main/java/cache/com/example/cachecontrol/CacheInterceptor.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java, tomcat/src/main/java/nextstep/jwp/controller/Controller.java, tomcat/src/main/java/nextstep/jwp/controller/FrontController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/auth/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/auth/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseBody.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseEntity.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeader.java
=> [톰캣 구현하기 - 3, 4단계] 아벨(신준혁) 미션 제출합니다. 

study/src/main/java/cache/com/example/GreetingController.java, study/src/main/java/cache/com/example/version/ResourceVersion.java, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/com/techcourse/web/HttpResponse.java, tomcat/src/main/java/com/techcourse/web/HttpStatusCode.java, tomcat/src/main/java/com/techcourse/web/annotation/Param.java, tomcat/src/main/java/com/techcourse/web/annotation/Query.java, tomcat/src/main/java/com/techcourse/web/annotation/Request.java, tomcat/src/main/java/com/techcourse/web/handler/LoginHandler.java, tomcat/src/main/java/com/techcourse/web/handler/PageHandler.java, tomcat/src/main/java/com/techcourse/web/handler/RequestHandler.java, tomcat/src/main/java/com/techcourse/web/handler/RequestHandlerMapper.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestReader.java, tomcat/src/test/java/com/techcourse/web/handler/LoginHandlerTest.java, tomcat/src/test/java/com/techcourse/web/handler/PageHandlerTest.java, tomcat/src/test/java/com/techcourse/web/handler/RequestHandlerMapperTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpRequestReaderTest.java
우테코 훈남 프린님 안녕하세요 ㅎㅎ 백엔드 상돌입니다.
말씀 드렸던 대로 일단 1단계만 구현해서 제출드려요.
기능 구현을 하다보니 리팩터링이 자연스레 된 부분이 몇몇 있습니다~ 하다보니 구조가 조금 더 복잡해지긴 했는데 확인해보시고 이해가 안 가는 곳이 있다면 바로 DM 주세요! 
리뷰는 천천히 그리고 편하게 부탁드려요.  감사합니다~!🫡
=> [톰캣 - 1단계] 상돌(이상진) 미션 제출합니다.

study/src/main/java/cache/com/example/GreetingController.java, study/src/main/java/cache/com/example/version/ResourceVersion.java, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/com/techcourse/controller/Controller.java, tomcat/src/main/java/com/techcourse/controller/FrontController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/HttpProtocol.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/resources/static/index.html, tomcat/src/main/resources/static/welcome.html, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
방가워요 메이슨~
우선 제 코드는 큰일이 나있습니다..
로우 레벨을 구현하라고 하니 막막해서 제대로 진행하지 못한 것 같아요
클래스 분리도 제대로 되지 않았고 아쉬움이 가득남은 코드입니다..
아무래도 다시 공부해서 싹 밀고 다시 만들어야할 것 같습니다..
가벼운 마음으로 리뷰해주셔도 좋을 것 같구.. 그냥 조언할 게 있다면 부탁드립니다..
근데 또 우테코의 목적이 돌아가는 쓰레기를 제한시간 내로 만드는 것 아니겠습니까
우선 돌아는가니까 참작 부탁드립니다 ㅎㅎ..
그리고 어쩌다보니 1,3단계를 하게 된 것 같아요
2,4 단계를 다음 리뷰에 선보일 예정이니 참고바랍니다:)
=> [1 -2단계 - Tomcat 구현하기] 이든(최승준) 미션 제출합니다.

study/build.gradle, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, study/src/test/java/cache/com/example/GreetingControllerTest.java, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/coyote/http11/FileReader.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestPath.java, tomcat/src/main/java/org/apache/coyote/http11/request/QueryString.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseBody.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseParser.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatusCode.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 테드!
오랜만입니다.
일전에 공유드렸던 대로 1단계를 완료하여 리뷰 요청을 보냅니다.
사실 구현에만 초점을 맞춘다면 2단계까지 완료할 수 있었을텐데, 구조 정리에 욕심이 나서 원하던 만큼 완료하지는 못했습니다.
그러다보니 3단계도 일부 구현하게 된 것 같네요.
다음 리뷰에 남은 단계들도 완료하여 리뷰를 요청하겠습니다.
아직 리팩토링할 요소들도 많이 남아있는데요, 편하게 리뷰해주시면 감사하겠습니다.
잘 부탁드립니다~!
=> [1단계 - Tomcat 구현하기] 메이슨(김경원) 미션 제출합니다.

study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/coyote/Processor.java, tomcat/src/main/java/org/apache/coyote/http11/FileExtensionType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpAcceptHeaderType.java, tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/Session.java, tomcat/src/main/java/org/apache/coyote/http11/SessionStorage.java, tomcat/src/main/java/org/apache/coyote/http11/SimpleHttpRequest.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/org/apache/coyote/http11/SimpleHttpRequestTest.java
안녕하세요 다온! 이렇게 리뷰어-리뷰이로 다시 만나니까 너무 반갑네요! 리뷰 잘 부탁드려요! 🤭
프로젝트 병행등 시간 부족으로 1-2단계 목표를 요구사항 구현으로 한정해서 작업했기 때문에 코드 퀄리티가 다소 떨어질 수 있습니다. 미흡한 부분은 모두 3단계 과정을 진행하면서 고칠 계획입니다.
개선 예정된 부분들은 다음과 같습니다.
- Class 분리 및 테스트 코드 작성
- ```null```을 리턴하는 로직이 예외를 던지도록 전부 개선
- Tomcat 로직과 Application Service 로직을 분리
- 부족한 예외 및 검증 로직 추가
- 몇몇 성능적으로 비효율적이라 판단되는 로직 개선
=> [1 -2단계 - Tomcat 구현하기] 켈리(양성욱) 미션 제출합니다

tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeader.java, tomcat/src/main/java/org/apache/coyote/http11/HttpReader.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 명오! 호기입니다!
이번주에 일정이 너무 많이 겹쳐있어서 의도치 않게 1단계만 내게 되었습니다..😂
빠른시일내에 나머지 step도 제출하겠습니다! 잘부탁드립니다!
=> [톰캣 구현하기 1단계] 호기(조호연) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/catalina/Session.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/RequestHandler.java, tomcat/src/main/java/org/apache/coyote/http11/RequestParser.java, tomcat/src/main/resources/static/login.html
안녕하세요 백호, 폰드입니다🙇‍♂️
대부분의 로직이 RequestHandler에 위치해서 코드가 지저분하네요.
하드 코딩한 부분도 있는 것 같은데, 다음 단계 리팩터링을 통해 개선하겠습니다!
감사합니다.
=> [2단계 - Tomcat 구현하기] 폰드(권규택) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/catalina/manager/Session.java, tomcat/src/main/java/org/apache/catalina/manager/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java
망쵸 안녕하세요~~ 아토입니다.
2단계의 나머지 부분인 쿠키(2.3)와 세션(2.3) 부분 구현했습니다!
크게 바뀐 부분은 없으니 추가된 부분 위주로 봐주시면 될 것 같아요.
메서드 순서를 좀 바꾸어서 깃허브에서 인식을 잘 못하는 것 같은데, 커밋 단위로 보시면 아마 보기 좀 더 편하실 겁니다!
잘 부탁드립니다 🥹
=> [Tomcat 구현하기 - 2단계] 아토(이혜린) 미션 제출합니다.

tomcat/src/main/java/org/apache/Method.java, tomcat/src/main/java/org/apache/coyote/controller/AbstractController.java, tomcat/src/main/java/org/apache/coyote/controller/Controller.java, tomcat/src/main/java/org/apache/coyote/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/controller/PageController.java, tomcat/src/main/java/org/apache/coyote/controller/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/Method.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/Status.java, tomcat/src/main/java/org/apache/coyote/http11/StatusLine.java
안녕하세요 폰드~! 이번 단계도 리뷰 잘 부탁드립니다 🙇‍♀️
=> [톰캣 구현하기 3단계] 제제 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Session.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/domain/Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/domain/HttpStatusCode.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 짱수!! 드디어 2단계를 완료해서 리뷰 요청드립니다~~
내일 모레가 마감일인데 이제 겨우 2단계라니 벌써부터 눈앞이 캄캄하군요ㅎㅎㅎ
하지만 가차없는 리뷰 부탁드립니다!!
1단계 코드와 구조가 정말 많이 바뀌었습니다..
처음에는 돌아가는 쓰레기를 만들자는 마음으로 코드를 작성했었는데 완성해보니 쓰레기라고 부르기에는 쓰레기에게 사과해야 할 것 같은 코드가 되어 있었습니다.
도저히 2단계 미션을 이어서 할 수가 없는 상태였습니다.그래서 클래스 분리를 시도했지만 쉽지 않더라구요...
또한 3단계 요구사항이 request, response, controller의 분리이기 때문에 이번에는 클래스 분리에 큰 목적을 두지 않았습니다!!
다만 3단계에서 보다 편하게 분리하기 위해 각각의 기능에 맞게 메서드를 분리해보았습니다.
가장 많이 고민했던 부분은 각 응답에 맞게 response header를 추가해주는 것이었습니다.
어찌저찌 구현하긴 했는데 맞게 구현했는지, 나중에 어떻게 분리해야 할 지는 잘 모르겠네요..ㅎㅎ
추가적으로, 테스트 코드가 전혀 작성되어 있지 않은데, 3단계를 하면서, 그리고 짱수의 리뷰를 기다리면서 조금씩 추가해보겠습니다..
테스트 코드의 중요성애 대해 7달 동안 교육 받았지만 여전히 쉽지 않네요.
1단계 때처럼 따끔하고 날카로운 리뷰 많이 부탁드립니다!!
=> [톰캣 구현하기 2단계] 초롱 미션 제출합니다

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, study/src/test/java/thread/stage2/TestHttpUtils.java, tomcat/src/main/java/org/apache/catalina/controller/AbstractController.java, tomcat/src/test/java/com/techcourse/controller/DefaultControllerTest.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/com/techcourse/controller/StaticResourceControllerTest.java, tomcat/src/test/java/com/techcourse/controller/model/AbstractControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/RequestProcessorTest.java, tomcat/src/test/java/org/apache/coyote/response/HttpResponseTest.java
안녕하세요 켬미! ☺️
따끈따끈한 3단계 코드를 가져왔습니다!
사실 1단계에서부터 구조에 틀을 좀 잡아놓아서 3단계 요구사항 예시에 맞춰 `AbstractController` 만 수정되었습니다!
그리고 **켬미가 이전 PR에서 제시해주신 피드백을 반영하여 `Test` 코드에서 몇가지는 `Assertions`를 사용하도록 변경했어요! 😋**
학습 테스트도 같이 작성하였으니 편하게 리뷰 해주세요! 
테스트도 정상구동도 확인했습니다!
=>  [3단계 - Tomcat 구현하기] 폴라(장유진) 미션 제출합니다.

tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/servlet/DefaultServlet.java, tomcat/src/main/java/org/apache/catalina/servlet/DispatcherServlet.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/RequestDispatcher.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/catalina/servlet/DefaultServletTest.java
안녕하세요롤롤로빈!
이번 단계에선 2단계에서 남겨주신 리팩토링 관련 리뷰를 반영하고 로직 분리를 진행했습니다!
이전에 남겨주신 학습 관련 질문은 시간 관계 상 남기지 못했습니다..ㅜㅜ
이후에 4단계 pr을 올릴 수 있게 된다면... 빠르게 남겨보겠습니다!
=> [3단계 - 톰캣 구현하기] 알파카(최휘용) 미션 제출합니다.

tomcat/README.md, tomcat/src/main/java/com/techcourse/service/SessionService.java, tomcat/src/main/java/com/techcourse/service/UserService.java, tomcat/src/main/java/org/apache/coyote/HomeServlet.java, tomcat/src/main/java/org/apache/coyote/HttpServlet.java, tomcat/src/main/java/org/apache/coyote/LoginServlet.java, tomcat/src/main/java/org/apache/coyote/RegisterServlet.java, tomcat/src/main/java/org/apache/coyote/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/Servlet.java, tomcat/src/main/java/org/apache/coyote/StaticResourceServlet.java, tomcat/src/main/java/org/apache/coyote/http/request/RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/HeaderName.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookies.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/ResourceReader.java, tomcat/src/main/java/org/apache/coyote/http11/StatusLine.java, tomcat/src/test/java/org/apache/coyote/HomeServletTest.java, tomcat/src/test/java/org/apache/coyote/LoginServletTest.java, tomcat/src/test/java/org/apache/coyote/RegisterServletTest.java, tomcat/src/test/java/org/apache/coyote/StaticResourceServletTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/ResourceReaderTest.java
안녕하세요 시소! 제리입니다 👋
미흡한 테스트 코드와 패키지 분리는 rc 남겨주시면 반영해서 다음 리뷰 요청을 보내겠습니다 
편하게 리뷰 남겨주세요! 잘 부탁드립니다
=> [3 단계 Tomcat 구현하기] 제리(김민정) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage2/TestHttpUtils.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RequestControllerMapper.java, tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java, tomcat/src/main/java/org/apache/coyote/http11/request/Http11RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/Http11RequestHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpMimeType.java, tomcat/src/main/java/org/apache/coyote/http11/response/Http11Response.java, tomcat/src/main/java/org/apache/coyote/http11/response/Http11ResponseHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatusCode.java, tomcat/src/main/resources/static/index.html, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/LoginControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RequestControllerMapperTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/Http11RequestBodyTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/Http11RequestHeadersTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/Http11RequestTest.java
안녕하세요 리니, 우주입니다!
레벨 4는 정말 바쁜 것 같네요 ㅠㅠ 미션에만 집중할 수 없는 환경이라 여러모로 부족한 점이 있지만
그래도 잘 부탁드리겠습니다!!!
=> [3단계 - Tomcat 구현하기] 우주(김성현) 미션 제출합니다.

study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
안녕하세요 페드로~ 감자입니다 🥔
4단계 미션도 잘부탁드려요
=> [4 단계 Tomcat 구현하기] 감자(김주하) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/request/Http11Request.java, tomcat/src/main/java/org/apache/coyote/session/Session.java, tomcat/src/main/java/org/apache/coyote/session/SessionManager.java
=> [4단계 - Tomcat 구현하기] 백호(전호건) 미션 제출합니다.

study/docs/appTest.md, study/src/main/java/thread/stage2/SampleController.java, study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, study/src/test/java/thread/stage2/TestHttpUtils.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/protocol/session/SessionManager.java
안녕하세요 초롱
4단계 구현하여 제출합니다.
잘 부탁드립니다!
=> [4단계 Tomcat 구현하기] 로키(정해성) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/BasicConnector.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/connector/ThreadPoolConnector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/org/apache/catalina/connector/ThreadPoolConnectorTest.java, tomcat/src/test/java/support/SlowHttp11Processor.java
테니, 안녕하세요~ 드디어 마지막이네요. 
커밋 단위로 보시면 리뷰하기 편하실 것 같아요. 
궁금한 점 있으면 편하게 질문 주세요! 
그동안 많이 배웠어요. 감사합니다. 🙇
=> [4단계 - Tomcat 구현하기] 망쵸(김주환) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java
안녕하세요 배키 
벌써 마지막 단계 제출일이네요.
학습 테스트와 4단계 미션를 모두 반영하였습니다.
궁금점이나 부족한점 모두 리뷰 부탁드려요 😄
=> [4단계 - Tomcat 구현하기] 다온(조형익) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/com/techcourse/controller/HelloController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatusLine.java
카피 안녕하세요. 냥인입니다. 😸
마지막 단계네요! 
리뷰 잘 부탁드립니다. 
즐(거운)추(석)요 ~ ~
=> [톰캣 구현하기 - 4단계] 냥인(최가희) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeader.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/resources/static/login.html, tomcat/src/main/resources/static/register.html, tomcat/src/test/java/org/apache/catalina/SessionManagerTest.java, tomcat/src/test/java/org/apache/catalina/SessionTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/HomeControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/LoginControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/PageControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RequestMappingTest.java
안녕하세요 레모네! 🍋
시간상의 이유로 리팩토링과 테스트를 완전하게 작성하지 못했어요
레모네와 리뷰를 주고받으며 보충해 나가겠습니다
(오늘 저녁에 보충 예정입니다 😖)
레모네도 미션 마감 파이팅입니다!
=> [4단계 - Tomcat 구현하기] 시소(신지송) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage0/ThreadTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, tomcat/src/main/java/com/techcourse/Application.java, tomcat/src/main/java/com/techcourse/controller/LoginRequestController.java, tomcat/src/main/java/com/techcourse/controller/RootRequestController.java, tomcat/src/main/java/com/techcourse/controller/SignupRequestController.java, tomcat/src/main/java/org/apache/NotFoundController.java, tomcat/src/main/java/org/apache/ObjectMapper.java, tomcat/src/main/java/org/apache/catalina/Session.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/container/Container.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/AbstractRequestController.java, tomcat/src/main/java/org/apache/coyote/NotFoundController.java, tomcat/src/main/java/org/apache/coyote/RequestHandlerMapper.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/com/techcourse/controller/NotFoundControllerTest.java, tomcat/src/test/java/org/apache/catalina/SessionManagerTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/NotFoundControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/response/Http11ResponseTest.java
안녕하세요. 커찬!
마지막 미션 리뷰 잘 부탁드립니다.
커찬한테 많이 배우고 싶네요 ^.^
=> [Tomcat 구현하기 - 4단계] 위브(김기범) 미션 제출합니다.

study/build.gradle, study/src/main/java/cache/com/example/GreetingController.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/resources/application.yml, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/com/techcourse/controller/Controller.java, tomcat/src/main/java/com/techcourse/controller/ControllerAdviser.java, tomcat/src/main/java/com/techcourse/controller/FrontController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/dispatcher/DispatcherServlet.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/MainPageControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/org/apache/coyote/http11/SessionManagerTest.java
안녕하세요 조조! 타칸입니다!
동시성 확장 코드가 적지만 이해하기 조금 어려운 부분이 있네요..
그래도 Connector에 대한 개념이 조금 잡혀서 구현할 수 있었습니다!
하지만 테스트는 어떤식으로 해야할지 아직 잘 모르겠어요 ㅠㅠ 일단 작성해보긴 했는데 이게 정말 동시성을 테스트할 수 있는지는 잘 모르겠습니다.. 계속 학습해보고 리뷰 주시면 반영해보거나 RC때 추가해보겠습니다! 😭
=> [4단계 - Tomcat 구현하기] 타칸(최원준) 미션 제출합니다.

README.md, study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage0/ThreadTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/auth/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/response/HttpResponse.java, tomcat/src/main/java/org/apache/catalina/response/ResponseHeader.java, tomcat/src/main/java/org/apache/catalina/response/StatusLine.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestProcessor.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/PageLoadControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RootControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
반가워요 폭포 ~!
이번엔 4단계를 들고왔어요 ! 스레드 풀이 낯설어서 여러가지 시도는 못하고 베이직하게 코드를 작성했습니다.
몇가지 고민 거리는 다음과 같습니다.
몇으로 설정하면 좋을까 하다 톰켓을 확인하니 200으로 되어있어 200으로 설정했습니다.
> https://tomcat.apache.org/tomcat-9.0-doc/config/http.html
> ![image](https://github.com/user-attachments/assets/0925b007-9201-4580-b694-a3ca23485860)
이미 ConcurrentHashMap 으로 설정해놔서 내부에서 lock을 걸텐데 SessionManage에서 할지 말지 고민이었어요.,!
결국 안전한게 최고니 syncronized을 걸었습니다..! 
폭포는 어떻게 생각하시나요?
사실 답을 찾지 못하였어요... 조금 더 고민해볼게요 ! 그리고 혹시 폭포는 4단계를 테스트했다면 어떻게 했는지 알려주세요 ~!
그리고 테스트가 있어야한다고 생각하는지도 알려주세요 ~!
=> [4단계 - Tomcat 구현하기] 켬미(김경미) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, tomcat/src/main/java/com/techcourse/controller/HomeController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/controller/AbstractController.java, tomcat/src/main/java/org/apache/catalina/controller/Controller.java, tomcat/src/main/java/org/apache/catalina/controller/NotFoundController.java, tomcat/src/main/java/org/apache/catalina/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/coyote/http/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/session/SessionManager.java, tomcat/src/test/java/com/techcourse/controller/HomeControllerTest.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java
안녕하세요 몰리 〰️ 
벌써 4단계네요! 
3단계 리뷰 반영과, 4단계에서 스레드 풀과 동시성을 학습하며 진행해보았습니다.
리뷰 잘 부탁드려요 🤗
추석 연휴도 잘 보내세요 ⍢♡
=> [4단계 - Tomcat 구현하기] 릴리(최윤서) 미션 제출합니다.

study/src/test/java/thread/stage0/ThreadPoolsTest.java, tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java, tomcat/src/main/java/org/apache/coyote/http11/exception/ClientRequestException.java, tomcat/src/main/resources/static/400.html, tomcat/src/test/java/org/apache/coyote/http11/controller/AbstractControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/LoginControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RootControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/exception/ErrorResponseHandlerTest.java, tomcat/src/test/java/support/HttpRequestBuilder.java
안녕하세요 프람 😄 포케입니다.
4단계 미션 제출합니다..! 
리뷰하실 때 오늘 수행한 학습테스트 리뷰도 [feat: thread 학습 테스트](https://github.com/woowacourse/java-http/pull/643/commits/67a5bbb91f9bde8880f39c135fcefb91dc9223bc) 부탁드립니다 🙏
=> [4단계 - Tomcat 구현하기] 포케(이무송) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/handler/StaticResourceHandler.java, tomcat/src/main/java/org/was/controller/FrontController.java, tomcat/src/main/java/org/was/converter/HttpResponseConverter.java, tomcat/src/main/java/org/was/session/SessionManager.java, tomcat/src/main/java/org/was/view/ViewResolver.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/org/was/session/SessionManagerTest.java
안녕하세요 타칸😊
마지막 단계네요. 일부 피드백 반영하여 리뷰 요청 드립니다.
4단계 요구사항과 모든 학습테스트 반영하였습니다.
=> [4 단계 Tomcat 구현하기] 테드(김규태) 미션 제출합니다.

tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/org/apache/catalina/servlet/DefaultServletTest.java
오랜 시간에 걸쳐 마지막 pr까지 드디어 왔네요..
갑자기 저번 주에 허리가 터져버려서 거의 4~5일 동안 아무 것도 못한 영향이 너무 컸던 것 같아요..(핑계임)
느린 pr 때문에 리뷰어인 로빈도 급하게 리뷰해주신 것 같아 죄송한 마음만 듭니다 😭 
와중에도 좋은 리뷰들 빠르게 남겨주셔서 너무 감사합니다!
학습 테스트를 이전 pr에 올렸어서 이번 file changes 수가 아주 적네요 ㅎㅎ
대신 스레드 풀 관련 학습을 팀원들과 아주아주 열심히 진행했습니다.
이전 pr에 남겨주신 학습 관련 리뷰에도 이제부터 열심히 달고, 다시 알려드리겠습니다!
이번에도 잘 부탁드립니다~ 🙇 
***
이전 pr 리뷰 확인해주세용~
[2단계](https://github.com/woowacourse/java-http/pull/630)
[3단계](https://github.com/woowacourse/java-http/pull/696)
로빈도 즐거운 추석 되십쇼~~ 🙇
=> [4단계 - Tomcat 구현하기] 알파카(최휘용) 미션 제출합니다

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/support/TestHttpUtils.java
안녕하세요! 어느덧 마지막 단계네요. 리뷰 잘 부탁드립니다!
1. 학습할 때 공부한 내용을 메모하는 용도로 주석을 사용했습니다.
2. 단독으로 테스트해야 동작하는 테스트가 있습니다. 다른 코멘트로 해당 위치에 남겨두겠습니다! 원인은 파악중인데 모르겠어요...
스레드 풀은 `Executors.newFixedThreadPool(int)` 를 살짝 변형하여 사용했습니다. 250개의 스레드가 모두 작업중인 경우 100개만 대기하게 하기 위해서 입니다.
=> [4단계 - 톰캣 구현하기] 로빈(임수빈) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/com/techcourse/controller/HomePageController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/test/java/com/techcourse/controller/HomePageControllerTest.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/com/techcourse/controller/StaticResourceControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RequestMappingTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestTest.java
안녕하세요 뽀로로~
4단계 구현하면서 이에 대한 테스트 코드는 어떻게 작성해야 할 지 감이 안 잡히네요.
3단계 머지하면서 말씀해주신 상수처리도 함께 반영했습니다!
마지막 리뷰 잘 부탁드립니다 :)
=> [4단계 - Tomcat 구현하기] 카고(정민호) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
안녕하세요 에버! 드디어 마지막 단계네요
2주동안 리뷰하시느라 고생많으셨습니다 :)
마지막까지 잘 부탁드려요
즐추~ 😊
=> [톰캣 구현하기 - 4단계] 프린(남기범) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage0/ThreadTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, study/src/test/java/thread/stage2/TestHttpUtils.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/Session.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/http11/Http11RequestHeader.java, tomcat/src/test/java/com/techcourse/db/InMemoryUserRepositoryTest.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/org/apache/catalina/controller/BodyParserTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11RequestBodyTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11RequestHandlerTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11RequestHeaderTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11RequestTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ResponseBodyTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ResponseHeaderTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ResponseTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpMethodTest.java, tomcat/src/test/java/support/TestHttpUtils.java
안녕하세요 제리!
4단계 동시성 확장하기와 Thread 학습 테스트를 진행하고 pr 보냅니다.
현재 테스트코드가 미비한 상황이라 추가하도록 하겠습니다!
정말 감사해요!! 🙇🏽‍♂️
=> [4단계 - Tomcat 구현하기] 이상(이건상) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage0/ThreadTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java
4단계 구현 마쳐서 제출합니다!
카고는 어떤 식으로 구현했는 지 궁금하네요!
=> [4단계 - Tomcat 구현하기] 도도(김도선) 미션 제출합니다

tomcat/src/main/java/com/techcourse/controller/AbstractController.java, tomcat/src/main/java/com/techcourse/controller/Controller.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/PageEndpoint.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/controller/StaticPageController.java, tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeaderKey.java, tomcat/src/main/java/org/apache/coyote/http11/RequestMapper.java, tomcat/src/main/java/org/apache/coyote/http11/cookie/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/cookie/HttpCookieExtractor.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/session/Session.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/RequestMapperTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpCookieExtractorTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestParserTest.java, tomcat/src/test/java/org/apache/coyote/http11/session/SessionTest.java
안녕하세요 테드!
3단계 기능 구현을 완료하여 리뷰를 요청합니다.
이번 3단계는 이전 단계에서 미리 분리를 해둔 덕에 변경점이 많지는 않네요.
아직 테스트 코드가 좀 부족합니다만,,, 피드백 반영하면서 더 추가해보도록 하겠습니다.
+) 4단계 내용은 새로 분리해서 올리도록 하겠습니다.
감사합니다.
=> [3단계 - Tomcat 구현하기] 메이슨(김경원) 미션 제출합니다.

study/src/main/resources/application.yml, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
안녕하세요 테드!
일전에 같이 올렸었던 Step 4 관련 코드를 새 PR로 분리하였습니다. 변경사항이 많지는 않네요.
이번 미션 마지막 단계도 잘 부탁드립니다!
=> [4단계 - Tomcat 구현하기] 메이슨(김경원) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/HttpSessionManger.java
안녕하세요, 상돌! 클로버입니다.
벌써 마지막 단계 리뷰 요청이네요~ 
4단계에서는 요구사항을 우선적으로 구현했습니다.
테스트 작성을 위해 꽤 오랜 시간 고민했는데 방법이 도저히 떠오르지 않아 일단 리뷰 요청 보냅니다 😢 
마지막 미션까지 잘 부탁드려요!
=> [4단계 - Tomcat 구현하기] 클로버(이은정) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/study/FileTest.java, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/common/HeaderKey.java, tomcat/src/main/java/org/apache/coyote/http11/request/Method.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/common/BodyTest.java, tomcat/src/test/java/org/apache/coyote/http11/common/HeadersTest.java, tomcat/src/test/java/org/apache/coyote/http11/common/VersionOfProtocolTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/MethodTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/PathTest.java, tomcat/src/test/java/org/apache/coyote/http11/response/HttpResponseTest.java, tomcat/src/test/java/org/apache/coyote/http11/servlet/RegisterServletTest.java, tomcat/src/test/java/org/apache/coyote/http11/session/SessionTest.java
안녕하세요 폴라 ! 🍇
4단계 미션 요구사항을 충족한 뒤 리뷰 요청 보냅니다. 
부족한 부분이 많을 것 같은데, 고민해본 후 보완해갈게요!
이번 미션도 잘 부탁드립니다. 😁
=> [4단계 - 톰캣 구현하기] 안나(김민겸) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, tomcat/src/main/java/com/techcourse/servlet/DispatcherServlet.java, tomcat/src/main/java/com/techcourse/servlet/RequestMapping.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/Session.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestStartLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/test/java/com/techcourse/servlet/RequestMappingTest.java, tomcat/src/test/java/org/apache/catalina/session/SessionManagerTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 구름! 커찬입니다.
스레드 학습 테스트까지 포함하여, 4단계 리뷰 부탁드립니다!
=> [4단계 - Tomcat 구현하기] 커찬(이충안) 미션 제출합니다.

study/src/main/java/thread/stage2/SampleController.java, study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/com/techcourse/controller/HomeController.java, tomcat/src/main/java/com/techcourse/controller/IndexController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/controller/ResourceController.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/ResponseHeader.java, tomcat/src/main/java/org/apache/coyote/http11/StatusLine.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpResponseTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/IndexControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/LoginControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/controller/ResourceControllerTest.java
안녕하세요 백호!
말씀하신대로 응답 객체 분리를 진행 하고 있습니다.
우선 4단계 요구사항에 대한 미션 제출하겠습니다!
감사합니다🙇‍♂️
=> [4단계 Tomcat 구현하기] 폰드(권규택) 미션 제출합니다.

tomcat/README.md, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java
안녕하세요 새양!
드디어 마지막 4단계 pr 제출이네요.
3단계 pr에서 스레드 테스트와 함께 커밋했더니
이번 pr에서는 변경 사항이 하나의 파일밖에 없네요ㅎㅎ
3단계를 진행하면서 `SessionManager`에 동시성 컬렉션을 적용했는데, 
변경 사항에 보이지 않아 따로 코드 첨부합니다!
``` java
public class SessionManager implements Manager {
private static final Map<String, Session> SESSIONS = new HashMap<>();
private static SessionManager SESSION_MANAGER;
private SessionManager() {}
@Override
public void add(final Session session) {
if (session.isInvalidate()) {
throw new IllegalStateException("무효화 된 세션입니다.");
}
SESSIONS.put(session.getId(), session);
}
@Override
public Session findSession(final String id) throws IOException {
if (SESSIONS.containsKey(id)) {
return validateSession(SESSIONS.get(id));
}
throw new IOException("세션 id가 존재하지 않습니다.");
}
public boolean isExistSessionId(final String sessionId) { …
```
=> [4단계 Tomcat 구현하기] 레모네(이지현) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/connector/Connector.java, tomcat/src/test/java/org/apache/catalina/session/SessionManagerTest.java
안녕하세요, 우주! 어느덧 마지막 단계이군요🙌
그럼 이번 단계도 리뷰 잘 부탁드립니다☺️
=> [Tomcat 구현하기 - 4단계] 산초(나영서) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/manager/SessionManager.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/org/apache/catalina/manager/SessionManagerTest.java
망쵸 안녕하세요~~~
드디어 마지막 단계네요...!!!
천천히 리뷰 주시죠 ㅎ ㅎ
잘 부탁드립니닷 💪
=> [Tomcat 구현하기 - 4단계] 아토(이혜린) 미션 제출합니다.

tomcat/src/main/java/com/techcourse/Application.java, tomcat/src/main/java/com/techcourse/servlet/LoginServlet.java, tomcat/src/main/java/com/techcourse/servlet/RegisterServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java
안녕하세요 메이슨 STEP4의 동시성 확장하기 미션 완료하였습니다.
`2. 동시성 컬렉션 사용하기` 는 제가 이미 처리해두었던 부분이라
`1. 동시성 확장하기` 만 구현하게 되었습니다.
동시성 확장 미션은 쓰레드값을 직접 제어하기 위해서 `newFixedThreadPool(maxThreads)` 을 사용하였습니다.
`CachedThreadPool`도 있지만 Fixed 방식의 고정값 쓰레드 풀을 선택한 이유는 CachedThreadPool은 쓰레드를 생성하고 삭제하는 과정들에 의해 성능이 좋지 않기 때문에 고정값을 설정하여 사용하고자 하였습니다.
maxThreads을 10으로 설정한 이유는 제 로컬 환경의 CPU가 10코어인데요
요청을 받을 때 컨텍스트 스위칭 발생을 최소화하고 최대 병렬 처리 성능을 발휘한다는 내용을 보고 동일하게 설정해보았습니다.
큰 수정은 없지만 리뷰 잘부탁드려요!
=> [Step4] 이든(최승준) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/http/session/SessionManager.java
프린 안녕하세요~ 
아직 쓰레드와 동시성에 대한 이해가 부족하여 일단 **기능 구현 완료 -> 정상 작동 여부 확인** 후 제출드립니다..ㅎㅎ
테스트도 어떻게 처리할지 애매해서 아직 작성하지 못했는데, 연휴 기간동안 최대한 보완해보도록 할게요.
행복한 명절 보내세요😄
=> [4단계 - 동시성 확장하기] 상돌(이상진) 미션 제출합니다.

tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/controller/AbstractController.java, tomcat/src/main/java/org/apache/coyote/controller/Controller.java, tomcat/src/main/java/org/apache/coyote/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/message/common/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/HttpRequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/HttpRequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/message/request/HttpRequestReader.java, tomcat/src/main/java/org/apache/coyote/http11/message/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/message/response/HttpResponseBody.java, tomcat/src/main/java/org/apache/coyote/session/Session.java, tomcat/src/main/java/org/apache/coyote/session/SessionManager.java, tomcat/src/main/java/org/apache/util/ResourceReader.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/org/apache/coyote/controller/HomeControllerTest.java, tomcat/src/test/java/org/apache/coyote/controller/StaticResourceControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpCookieTest.java, tomcat/src/test/java/org/apache/coyote/http11/message/common/HttpHeadersTest.java, tomcat/src/test/java/org/apache/coyote/http11/message/request/HttpRequestTest.java
안녕하세요 도비😈 
4단계 요구사항에 맞춰 작성했습니다. 
지난 PR에 대한 리뷰 반영은 조금씩 추가할 예정입니다. 
따라서 천천히 리뷰 해주셔도 좋을 것 같습니다ㅎㅎ
추석 잘보내고 오세요~~🙇🏻‍♂️
=> [4단계 - 톰캣 구현하기] 러쉬(이태훈) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/Session.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/controller/AbstractController.java, tomcat/src/main/java/org/apache/coyote/controller/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/StatusLine.java, tomcat/src/main/java/org/apache/coyote/util/ResourceHandler.java, tomcat/src/test/java/com/techcourse/controller/LoginControllerTest.java, tomcat/src/test/java/com/techcourse/controller/NotFoundControllerTest.java, tomcat/src/test/java/com/techcourse/controller/RegisterControllerTest.java, tomcat/src/test/java/org/apache/coyote/controller/AbstractControllerTest.java, tomcat/src/test/java/org/apache/coyote/controller/RequestMappingTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/RequestFormatterTest.java, tomcat/src/test/java/utils/TestFixtures.java
안녕하세요 아루~ 🙇🏻‍♀️ 
어느덧 마지막 단계로군요... 헤어지기 싫어요~ 계속 제 코드 리뷰 해주세요~~
에... 어쨌든 4단계는 우선 요구사항만 만족시켜두고 빠르게 찾아뵈었습니다.
절대적인 코드 변경량 자체가 크지 않아서 차라리 리뷰 텀을 짧게 가져가는 게 낫겠다 싶었어요.
- 지난 피드백 반영은 이번 리뷰 사항 반영과 동시에 진행해보려고 합니다.
이번 미션을 진행하면서 궁금했던 건... 아무래도 테스트 쪽인데요.
스레드 설정이나, 동시성 컬렉션을 적용하게 되면서 '과연 이게 잘 돌아가고 있는 건가?' 싶은 생각이 계속 들더라고요.
그런데 이런 부분을 어떻게 테스트하면 좋을지 감이 잘 잡히지 않고 있는 것 같습니다. 그래서 우선 코드만 작성해두었어요. 🤔 
아루는 어떠셨나요?
---
<br>
- 왜 MAX_SIZE 250으로 하셨나요?
그냥... ㅎㅎ
LMS 질문에 대한 답변이라고 생각하고 달아두었습니다. 성능은 크게 고려하지 않았어요. 
CPU 코어 개수가 8개라고 하니 그 근방이어도 좋을 것 같다는 생각이 드네요... 
<br>
- 왜 `submit`으로 설정하셨나요?
`execute`는 결과값을 반환하지 않고, 따라서 작업 진행 상태를 추적할 수 없다는 점이 가장 큰 디메리트로 느껴졌어요.
<br>
- 왜 Session과 SessionManager에만 동시성 컬렉션 적용하셨나요?
`Map`을 사용하고 있는 다른 클래스들로는 `header`, `HttpCookies` 이렇게 둘이 있는데요.
다른 사용자들이 요청하는 것들을 처리하다 동시성 이슈가 생길 만한 부분은 아니라고 생각했습니다.
---
그럼 …
=> [4단계] 애쉬 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/com/techcourse/Application.java, tomcat/src/main/java/com/techcourse/controller/GreetingController.java, tomcat/src/main/java/com/techcourse/controller/HttpController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/controller/ResourceFinder.java, tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java, tomcat/src/main/java/com/techcourse/model/User.java, tomcat/src/main/java/com/techcourse/session/Session.java, tomcat/src/main/java/com/techcourse/session/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Controllers.java, tomcat/src/main/java/org/apache/catalina/startup/WAS.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpPayload.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/requestline/HttpLocation.java, tomcat/src/main/java/org/apache/coyote/http11/request/requestline/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/request/requestline/HttpRequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/test/java/org/apache/coyote/http11/ThreadTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpCookieTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/requestline/HttpMethodTest.java
안녕하세요 조이썬!
3단계 피드백 반영 완료해서 마지막 단계 리뷰 요청드려요
특히 `세션에 대한 다양한 리다이렉션`에 대해 고민해봤는데 정말 재밌었어요.
처음 로그인이나 회원가입에 성공하면 greeting페이지로, 그 이후에 로그인이나 회원가입 페이지로 이동하려고하면 홈페이지로 리다이렉션할 수 있게 해보았습니다.
마지막까지 미리 감사합니다!
=> [4단계] 종이 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/com/techcourse/servlet/HomeController.java, tomcat/src/main/java/com/techcourse/servlet/LoginController.java, tomcat/src/main/java/com/techcourse/servlet/RegisterController.java, tomcat/src/main/java/jakarta/servlet/StaticResourceController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/servlets/StaticResourceController.java, tomcat/src/main/java/org/apache/catalina/session/Session.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpUtil.java, tomcat/src/test/java/com/techcourse/servlet/StaticResourceControllerTest.java, tomcat/src/test/java/org/apache/coyote/http11/ContentTypeTest.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/HttpUtilTest.java
안녕하세요 땡이!
리뷰 주셨던 것들은 대부분 반영했고
세션 관련된 캡슐화는 개인적으로 좀 고민하고 있어요! 
세션 매니져는 누가 들고 있어야 하며 세션 관련된 책임은 누구의 것인지 고민이 좀 되는데 
세션 매니져를 컨트롤러(서블릿)이 알아도 되는지? 
땡이의 의견이 궁금해요!
동시성에 대한 다양한 이야기를 나누는 것도 재미있겠네요.
마지막 까지 좋은 리뷰나눠요!
=> [STEP-4] 테바의 톰캣 구현하기 리뷰 요청입니다~
