study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/nextstep/jwp/model/HttpCookie.java, tomcat/src/main/java/nextstep/jwp/model/Session.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeaderType.java, tomcat/src/main/java/org/apache/coyote/http11/HttpHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequestParser.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpStatusCode.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/main/resources/static/login.html
안녕하세요, 에밀 ~! 라온입니다!
톰캣 구현하기 1, 2단계 잘 부탁드립니다 ~!
굴러는 가지만 .. 아직 전체적인 리팩토링이 많이 필요하고 .. 테스트를 하나도 안짰네요 ㅎㅎ .. 
전체적인 구조는 아래와 같습니다! 
1. Client 요청 후 Http11Processor에 전달
3. HttpRequestParser로 HttpRequest 생성
4. handleRequest() 메서드를 통해 핸들링 후 HttpResponse 반환
리뷰 반영하면서 추가적으로 request를 핸들링하는 클래스와 테스트들도 추가해보겠습니다!
리뷰 잘 부탁드립니다!
감사합니다 🙇‍♂️🙇‍♂️
=> [톰캣 구현하기 - 1, 2단계] 라온(문채원) 미션 제출합니다. 

study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/docs/README.md, tomcat/src/main/java/nextstep/jwp/exception/InvalidRequestMethod.java, tomcat/src/main/java/nextstep/jwp/handler/HandlerAdaptor.java, tomcat/src/main/java/nextstep/jwp/handler/HomeHandler.java, tomcat/src/main/java/nextstep/jwp/handler/IndexHandler.java, tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java, tomcat/src/main/java/nextstep/jwp/handler/RegisterHandler.java, tomcat/src/main/java/nextstep/jwp/handler/RequestHandler.java, tomcat/src/main/java/nextstep/jwp/handler/ResourceHandler.java, tomcat/src/main/java/nextstep/jwp/http/ContentType.java, tomcat/src/main/java/nextstep/jwp/http/FormData.java, tomcat/src/main/java/nextstep/jwp/http/HttpBody.java, tomcat/src/main/java/nextstep/jwp/http/HttpCookie.java, tomcat/src/main/java/nextstep/jwp/http/HttpHeaders.java, tomcat/src/main/java/nextstep/jwp/http/HttpMethod.java, tomcat/src/main/java/nextstep/jwp/http/HttpRequest.java, tomcat/src/main/java/nextstep/jwp/http/HttpResponse.java, tomcat/src/main/java/nextstep/jwp/http/HttpStatus.java, tomcat/src/main/java/nextstep/jwp/http/HttpUri.java, tomcat/src/main/java/nextstep/jwp/http/HttpVersion.java, tomcat/src/main/java/nextstep/jwp/http/QueryString.java, tomcat/src/main/java/nextstep/jwp/security/Session.java, tomcat/src/main/java/nextstep/jwp/security/SessionManager.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/resources/static/login.html
안녕하세요 에단 ! 
처음에는 그냥.. 하나의 클래스에서 다 구현하다가, 도저히 안 되겠다 싶어서 클래스 분리를 했더니 3단계가 리팩토링이더라구요..
되돌리기에는 너무 늦어버렸고, 시간은 촉박하고 ㅠㅠ 정말 부족함이 많아 보이는 코드입니다.
솔직하고, 공격적인 리뷰 부탁드립니다 ! 많이 배워가고 싶습니다 😄
로직의 흐름이 간단한데, 코드가 지저분해서 리뷰하시는데에 도움이 될까 싶어 간단하게 남깁니다 !
1. 요청을 받아서 `HttpRequest` 객체로 파싱한다.
2. 요청 URL을 통해, `HandlerAdaptor`에서 요청을 처리할 Handler를 결정한다.
3. 로직(?)을 수행하고, `HttpResponse` 객체를 반환한다.
=> [톰캣 구현하기 1, 2단계] 쥬니(전정준) 미션 제출합니다.

study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, tomcat/src/main/java/org/apache/cookie/Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/http/ContentType.java, tomcat/src/main/java/org/apache/http/Cookie.java, tomcat/src/main/java/org/apache/http/HttpHeaders.java, tomcat/src/main/java/org/apache/http/HttpStatus.java, tomcat/src/main/java/org/apache/session/Session.java, tomcat/src/main/java/org/apache/session/SessionManager.java, tomcat/src/main/resources/static/login.html, tomcat/src/main/resources/static/register.html
안녕하세요 가비, 엔델입니다.
HTTP에 대한 이해도가 부족하다보니 미션 구현에 집중했던 것 같아요. 마침 3단계가 리팩토링이기도 하니 메서드 분리를 최대한 하는 방향으로 진행했습니다.
흐름은 아래와 같습니다.
1. Http11Processor클래스의 process 메서드에서 시작합니다.
2. BufferedReader를 통해 requestLine, header, requestBody를 파싱합니다.
3. requestLine에서 다시 method, path, queryString을 파싱합니다.
4. controller에서 요청을 처리하고 response를 생성합니다.
````
4-1. if 분기를 통해 method와 path에 따라 다르게 처리합니다.
4-2. redirect인 경우, result를 만드는 경우(현재의 경우 파일을 전송하는 경우) generateResult, 단순히 string만 보내는 경우( 현재의 경우 "Hello world!" 전송하는 경우) generateResponseBody에 따라 다른 결과를 만듭니다. 이때 쿠키가 들어가는 경우에 따라 메서드가 오버로딩 되어있습니다.
````
5. outputStream.write를 합니다.
현재 가장 큰 문제는 구현에 집중하기 위해 Cookie, Session 등을 제외한 클래스 분리가 되어있지 않은 것입니다.
특히 Header나 Cookie가 Optional하게 들어가는 경우가 많은데 이를 위하다보니 코드가 많이 복잡해진 것 같습니다.
이점 참고해주시면 감사하겠습니다.
=> [톰캣 구현하기 - 1,2단계] 엔델(김민준) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/detector/FileDetector.java, tomcat/src/main/java/org/apache/coyote/handler/DynamicHandler.java, tomcat/src/main/java/org/apache/coyote/handler/Handler.java, tomcat/src/main/java/org/apache/coyote/handler/HandlerComposite.java, tomcat/src/main/java/org/apache/coyote/handler/LoginHandler.java, tomcat/src/main/java/org/apache/coyote/handler/StaticFileHandler.java, tomcat/src/main/java/org/apache/coyote/handler/StaticHandler.java, tomcat/src/main/java/org/apache/coyote/handler/WelcomePageHandler.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/parser/StaticFileParser.java, tomcat/src/main/java/org/apache/coyote/request/Body.java, tomcat/src/main/java/org/apache/coyote/request/HttpRequest.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/detector/FileDetectorTest.java, tomcat/src/test/java/org/apache/coyote/handler/LoginHandlerTest.java, tomcat/src/test/java/org/apache/coyote/handler/StaticFileHandlerTest.java, tomcat/src/test/java/support/fixture/HandlerFixtures.java
안녕하세요 땡칠 !
이번 미션을 진행하면서 2단계는 조금 더 학습이 필요하다고 생각이 들어서 1단계만 제출해보겠습니다,,
리뷰 받으면서 테스트랑 기능을 천천히 만들어가볼게요!
감사합니다~
=> [톰캣 구현하기 1단계] 우르(김현우) 미션 제출합니다

study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/catalina/Session.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/ExceptionHandler.java, tomcat/src/main/java/org/apache/coyote/http11/FormData.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/HttpException.java, tomcat/src/main/java/org/apache/coyote/http11/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/http11/ResourceLoader.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
=> [톰캣 구현하기 1, 2단계] 오도(문민혁) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/handler/Handler.java, tomcat/src/main/java/org/apache/coyote/handler/dynamichandler/AbstractHandler.java, tomcat/src/main/java/org/apache/coyote/handler/dynamichandler/HelloHandler.java, tomcat/src/main/java/org/apache/coyote/handler/dynamichandler/LoginHandler.java, tomcat/src/main/java/org/apache/coyote/handler/dynamichandler/RegisterHandler.java, tomcat/src/main/java/org/apache/coyote/handler/statichandler/ExceptionHandler.java, tomcat/src/main/java/org/apache/coyote/handler/statichandler/StaticHandler.java, tomcat/src/main/java/org/apache/coyote/handlermapping/HandlerMapping.java, tomcat/src/main/java/org/apache/coyote/http11/Body.java, tomcat/src/main/java/org/apache/coyote/http11/Header.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Query.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestReader.java, tomcat/src/main/java/org/apache/coyote/http11/request/StartLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseWriter.java
안녕하세요 매튜 ~ 반가워용 ~
스텝 3와 4를 하고 PR 보냅니다 !
저번에 주신 리뷰는 반영 다 했어요 ㅎㅎ
로직의 큰 흐름은 변함이 없지만, 이제 `HttpResponse`를 외부에서 생성 후 `Handler`에게 넘겨주어요 !
그래서 완벽한 `Response`를 생성과 동시에 만들 수 없어, `setter`를 열었습니다 !
요구사항을 지키기 위해 이렇게 했는데 구구가 이유는 다음시간에 알려준다해서 정말 궁금하네요 !
이번에도 잘 부탁드립니다 (하트)
=> [톰캣 구현하기 - 3, 4단계] 하디(전동혁) 미션 제출합니다.

tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/nextstep/jwp/exception/UserAlreadyExistException.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/controller/AbstrcatController.java, tomcat/src/main/java/org/apache/catalina/controller/Controller.java, tomcat/src/main/java/org/apache/catalina/controller/DefaultController.java, tomcat/src/main/java/org/apache/catalina/controller/RequestMapperImpl.java, tomcat/src/main/java/org/apache/catalina/exception/CustomBadRequestException.java, tomcat/src/main/java/org/apache/catalina/session/Session.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestMapper.java, tomcat/src/main/java/org/apache/coyote/http11/exception/HostingFileNotFoundException.java, tomcat/src/main/java/org/apache/coyote/http11/exception/MissingRequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestCookie.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpContentType.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpStatus.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 허브!!
3-4단계 미션 제출합니다 라고 하고,, 일단은 3단계만 진행이 되어서 우선 제출합니다..ㅠㅜ
코멘트 주시면 반영하면서 4단계도 같이 해 놓겠습니다ㅠ
지난 미션에서 `instanceof`로 검증한 이유 [질문](https://github.com/woowacourse/jwp-dashboard-http/pull/393#discussion_r1318602495) 대한 대답은 아래와 같습니다.
로그인한 회원 정보가 있는지 확인하는데, 세션에 해당 "user"라는 attribute가 있는지만으로 될까..? 해당 attribute가 User임을 확인을 해야하지 않을까..? 라는 생각으로 하게 되었습니다..
Session의 map에서 value를 Object로 관리하기 때문에 적절한 객체가 들어가있는지 판단이 필요하다는 생각이였습니다. 그렇다고 Session내부에서 User클래로 캐스팅을 하는등의 처리를 하기에는 apache 패키지에서 도메인 클래스에 의존성이 생기기에, 안하는것이 좋을 것 같다고 생각을 하였기 때문입니다..!
---
이번 미션을 진행하며 `Controller`, `AbstrcatController`는 `catalina`패키지에 두었고, 해당 `AbstractController`를 상속받는 `LoginController`, `RegisterController`들은 jwp 패키지에 두었습니다.
마음같아서는 RequestMapper에서도 jwp패키지로의 의존성을 끊어야 겠다고 생각을 했는데 아직 어떻게 하면 좋겠다라는 마땅한 생각이 안나서 처리하지는 못하였습니다..ㅠㅜ
좋은 방법이 …
=> [톰캣 구현하기 - 3, 4단계] 필립(양재필) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/controller/IndexPageController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponseHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/session/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/test/java/org/apache/coyote/http11/session/HttpCookieTest.java
안녕하세요 준팍! 
3단계에서 피드백 줬던 내용 중에서 service 메서드 시그니처 바꾸는 것도 함께 반영했어요! 
(패키지 의존성 분리는 아직 잘 모르겠어서 일단 남겨두었슴니다.....!)
쓰레드 관련해서는 이번에 처음 공부해봐서 잘 했을지 모르겠는데, 많이 피드백 주세요!
쓰레드 테스트 코드는 어떻게 작성해야 할지 모르겠어서 일단 남겨두었습니다. 
다음 리뷰요청때까지 좀더 공부해볼게요 혹시 알면 알려주세요 ㅎㅎㅎ
=> [톰캣 구현하기 - 4단계] 깃짱(조은기) 미션 제출합니다.

study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/common/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/common/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/common/request/HttpMethod.java, tomcat/src/main/java/org/apache/coyote/http11/common/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/common/request/RequestHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/common/request/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/common/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/common/response/ResponseHeaders.java, tomcat/src/main/java/org/apache/coyote/http11/exception/BadRequestException.java, tomcat/src/main/java/org/apache/coyote/http11/exception/MethodNotAllowedException.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/HelloWorldServlet.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/LoginServlet.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/NotFoundServlet.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/Page.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/RegisterServlet.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/Servlet.java, tomcat/src/main/java/org/apache/coyote/http11/servlet/StaticResourceServlet.java, tomcat/src/test/java/org/apache/coyote/http11/common/ContentTypeTest.java, tomcat/src/test/java/org/apache/coyote/http11/common/request/RequestHeadersTest.java, tomcat/src/test/java/org/apache/coyote/http11/common/request/RequestLineTest.java, tomcat/src/test/java/org/apache/coyote/http11/common/response/HttpResponseTest.java
안녕하세요 하디 🕺
이번 미션 3,4단계 완료했습니다!
3단계(리팩토링)를 진행하다보니 수정사항이 꽤 많이 생겼습니다 ㅎㅎ..
1. Servlet
기존 Servlet의 handle메소드는 Request를 파라미터로 받아 적절한 Response를 반환했습니다.
수정 후 Servlet의 service메소드가 Request, Response를 모두 파라미터로 받고,
service 로직 속에서 response에 적절한 값을 세팅해주게 되었습니다.
2. MethodNotAllowedException & BadRequestException
허용하지 않는 메소드이거나 잘못된 요청인 경우 error를 발생시키고
Http11Processor에서 해당 error를 잡아 적절한 response를 세팅하도록 수정했습니다.
3. HttpHeaders -> RequestHeaders & ResponseHeaders
HttpRequest, HttpResponse 모두에서 사용되던 HttpHeaders를 RequestHeaders와 ResponseHeaders로 분리했습니다.
이번 리뷰도 잘 부탁드립니다!! 🙇‍♀️
=> [톰캣 구현하기 - 3, 4단계] 오잉(이하늘) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage1/Users.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/Headers.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/StatusCode.java, tomcat/src/main/java/org/apache/coyote/http11/ViewLoader.java, tomcat/src/main/java/org/apache/coyote/http11/controller/AbstractController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/ErrorController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/LoginController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RegisterController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/StaticController.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/QueryString.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/test/java/org/apache/coyote/http11/RequestMappingTest.java
안녕하세요. 엔델
3단계 요구사항 까지 구현은 했는데 
4단계는 아직 구현을 다 못했습니다..
4단계는 3단계 요구사항과 같이 반영해도 될까요?
=> [톰캣 구현하기 3, 4단계] 호이(이건호) 미션 제출합니다. 

README.md, tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java, tomcat/src/main/java/nextstep/jwp/controller/DefaultController.java, tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/nextstep/jwp/controller/RootController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/manager/SessionManager.java, tomcat/src/main/java/org/apache/coyote/Controller.java, tomcat/src/main/java/org/apache/coyote/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/common/ContentType.java, tomcat/src/main/java/org/apache/coyote/common/Headers.java, tomcat/src/main/java/org/apache/coyote/common/HttpCookie.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/request/HttpRequestBody.java, tomcat/src/main/java/org/apache/coyote/request/HttpRequestHeader.java, tomcat/src/main/java/org/apache/coyote/request/HttpRequestLine.java, tomcat/src/main/java/org/apache/coyote/request/RequestUri.java, tomcat/src/main/java/org/apache/coyote/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/response/HttpStatus.java, tomcat/src/main/java/org/apache/coyote/response/StatusLine.java, tomcat/src/main/java/org/apache/coyote/utils/FileUtils.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 로건 
1,2 단계때 좋은 리뷰 덕분에 놓치고 있던 부분을 많이 잡을 수 있었어요 감사합니다 👍
이전 PR 에 대한 답은 아래 링크에서 확인 부탁드립니다!
https://github.com/woowacourse/jwp-dashboard-http/pull/355
이전에 HttpResponse 객체는 builder 패턴을 사용해서 구현했었는데 요구사항에서 Controller 의 파라미터를 건드리면 안되어서 매개변수로 들어오는 HttpResponse 에 값을 넣어주려다보니 어쩔수 없이 setter 를 많이 사용하게 되어버렸는데요..!
혹시 로건은 Controller 의 파라미터를 안건드리면서 response 값을 어떻게 세팅해주셨는지 궁금합니다
그리고 예외상황에 대한 처리가 좀 미흡한거같아서 로건이 알고있는 예외상황(?) 에 대한 조언도 주시면 감사합니다!!
3,4단계 리뷰도 잘 부탁드립니다 🌱
=> [톰캣 구현하기 - 3, 4 단계] - 제나(위예나) 미션 제출합니다

tomcat/src/main/java/nextstep/jwp/controller/AbstractController.java, tomcat/src/main/java/nextstep/jwp/controller/FileController.java, tomcat/src/main/java/nextstep/jwp/controller/HelloController.java, tomcat/src/main/java/nextstep/jwp/controller/LoginController.java, tomcat/src/main/java/nextstep/jwp/controller/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/request/Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/session/Session.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/util/PathFinder.java, tomcat/src/main/java/org/apache/coyote/http11/util/QueryParamsParser.java, tomcat/src/main/resources/static/400.html
안녕하세요 모디!
중요한 내용 위주로 코멘트를 주셔서 정말 감사합니다!
코멘트 주신 내용(구조 변경) 중에 아직 반영하지 못한 내용이 있는데요.
해당 내용은 최대한 빨리 반영해보겠습니다!
감사합니다!
=> [톰캣 구현하기 3, 4단계] 로이 미션 제출합니다.

study/src/main/java/cache/com/example/cachecontrol/CacheControlInterceptor.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, study/src/test/java/thread/stage0/ThreadPoolsTest.java, tomcat/src/main/java/nextstep/jwp/exception/ResourceNotFoundException.java, tomcat/src/main/java/nextstep/jwp/presentation/AbstractController.java, tomcat/src/main/java/nextstep/jwp/presentation/Controller.java, tomcat/src/main/java/nextstep/jwp/presentation/ControllerType.java, tomcat/src/main/java/nextstep/jwp/presentation/IndexController.java, tomcat/src/main/java/nextstep/jwp/presentation/LoginController.java, tomcat/src/main/java/nextstep/jwp/presentation/MainController.java, tomcat/src/main/java/nextstep/jwp/presentation/OtherController.java, tomcat/src/main/java/nextstep/jwp/presentation/RegisterController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/request/FileReader.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/response/FileReader.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/Session.java, tomcat/src/main/java/org/apache/coyote/http11/response/SessionManager.java, tomcat/src/test/java/nextstep/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestTest.java, tomcat/src/test/java/org/apache/coyote/http11/response/HttpResponseTest.java
안녕하세요 메리🎄
말씀해주신 request body의 포맷 처리 부분은 RequestBody 객체를 하나 만들어서 Content-Type에 따라 분기처리가 가능할 수 있도록 확장성을 열어두었습니다.
다만 지금 미션에선 application/x-www-form-urlencoded 타입만 다루고 있는 것 같아 다른 타입에 대한 처리는 해주지 않았습니다.
감사합니다.
=> [톰캣 구현하기 3, 4단계] 키아라(김도희) 미션 제출합니다

tomcat/src/main/java/nextstep/jwp/handler/HelloController.java, tomcat/src/main/java/nextstep/jwp/handler/LoginController.java, tomcat/src/main/java/nextstep/jwp/handler/LoginHandler.java, tomcat/src/main/java/nextstep/jwp/handler/RegisterController.java, tomcat/src/main/java/nextstep/jwp/handler/RegisterHandler.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/HttpTarget.java, tomcat/src/main/java/org/apache/coyote/http11/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/TargetPath.java, tomcat/src/main/java/org/apache/coyote/http11/controller/Controller.java, tomcat/src/main/java/org/apache/coyote/http11/controller/FileController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/GetAndPostController.java, tomcat/src/main/java/org/apache/coyote/http11/controller/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/handler/FileHandler.java, tomcat/src/main/java/org/apache/coyote/http11/handler/GetAndPostHandler.java, tomcat/src/main/java/org/apache/coyote/http11/handler/Handler.java, tomcat/src/main/java/org/apache/coyote/http11/header/Cookies.java, tomcat/src/main/java/org/apache/coyote/http11/header/Headers.java, tomcat/src/main/java/org/apache/coyote/http11/session/Session.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/test/java/org/apache/coyote/http11/HttpRequestTest.java, tomcat/src/test/java/org/apache/coyote/http11/TargetPathTest.java, tomcat/src/test/java/org/apache/coyote/http11/session/SessionManagerTest.java
안녕하세요 히이로! 지난 리뷰에 이어 잘 부탁드립니다
특이사항은 Controller(Handler) 인터페이스를 요구사항에 맞춰 다음과 같은 형태로 변경하게 되었습니다.
```java
public interface Handler {
void handle(HttpRequest request, HttpResponse response) throws Exception;
}
```
이 형태가 response가 어디서든 수정 가능하다는 장점은 있지만, 이런 형태가 꼭 필요한 것인지 아직은 잘 모르겠습니다 ㅠㅠ
오히려 이렇게 바꾸다보니 어디서 수정되었는지 예측하기 어려워서 디버깅이 더 어려워진다는 단점이 있었어요.
히이로는 핸들러가 왜 이런 형태를 가져야 한다고 생각하시는지 궁금합니다.
=> [톰캣 구현하기 - 3, 4단계] 땡칠(박성철) 미션 제출합니다. 

study/src/main/java/cache/com/example/GreetingController.java, study/src/main/java/cache/com/example/version/ResourceVersion.java
- `javax`로 작성된 import가 dependency에 존재하지 않아서, `jakarta` 버전으로 import문을 수정합니다.
=> fix: replace javax with jakarta on imports

study/build.gradle
- `Thread` 학습 테스트를 위해 `thread.stage2.App` 을 실행하면 `NoSuchFieldError` 발생
```
Logging system failed to initialize using configuration from 'null'
java.lang.NoSuchFieldError: Class ch.qos.logback.classic.LoggerContext does not have member field 'java.util.concurrent.locks.ReentrantLock configurationLock'
at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:364)
...
10:45:41.445 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
```
- `ch.qos.logback:logback-classic` 최신 버전 `1.5.7` 이 `Spring Boot` `3.3.0` 과 호환되지 않는 것으로 추정
- 커밋 https://github.com/woowacourse/java-http/commit/92a84f2d5f81a84e4164a1f8ec1e8db337ba06a9 에서 버전 업데이트가 이루어진 이력이 있음
- `org.springframework.boot:spring-boot-starter-logging:3.3.0` 에서 `logback-classic 1.5.6` 을 포함하고 있으므로 `implementation …
=> fix: remove implementation logback-classic on gradle

study/src/main/resources/application.yml
- `Thread` 학습 테스트를 위해 `thread.stage2.App` 을 실행하면 발생 아래 오류 발생
- `Spring Boot 3.3.0` 버전 에서 `application.yml` 에 기존 설정 되어 있던 `Tomcat` 스레드 설정 값 `server.tomcat.threads.max` 이 `2` 로써 최소 스레드 유지 개수보다 낮게 설정 되어 있음
- `server.tomcat.threads.min-spare=2` 를 추가하여 `max` 와 같도록 설정 (기본값: 10)
- https://github.com/spring-projects/spring-boot/issues/40945
> 참고자료에 따르면 이 문제는 `Spring Boot 3.3.1` 에 해결되었다고 합니다.
`CachedThreadPool` 을 이해하기에도 좋은 옵션이지 않을까 생각하였습니다.
=> fix: add threads min-spare configuration on properties

study/build.gradle, study/src/main/java/cache/com/example/cachecontrol/CacheInterceptor.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestHandler.java
안녕하세요 백호! BE 폰드입니다.🙇
웹 서버 구현이라기 보다는 미션 요구 사항만 최소한으로 지키게 되었네요..
따끔한 리뷰 해주십쇼..
감사합니다!
=> [1단계 Tomcat 구현하기] 폰드(권규택) 미션 제출합니다.

study/build.gradle, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/java/cache/com/example/version/HandlebarsConfig.java, study/src/main/java/cache/com/example/version/VersionHandlebarsHelper.java, study/src/main/resources/application.yml, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/com/techcourse/controller/ApiRouter.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/db/InMemoryUserRepository.java, tomcat/src/main/java/com/techcourse/model/User.java, tomcat/src/main/java/com/techcourse/util/FileReader.java, tomcat/src/main/java/com/techcourse/util/StaticResourceManager.java, tomcat/src/main/java/org/apache/catalina/Session.java, tomcat/src/main/java/org/apache/catalina/SessionManager.java, tomcat/src/main/java/org/apache/coyote/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/MediaType.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpResponse.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/support/StubSocket.java
안녕하세요 재즈!
우연히 같은 팀원을 리뷰어로 만나게 되니 반갑네요.
3단계가 리팩토링으로 알고 있어서, 3단계까지 완료 휴 PR을 남기려고 했는데 여러 이유로 2단계까지만 완료하고 PR을 작성하게 됐어요.
때문에 코드가 아주.. 마음에 들지는 않네요.
객체 분리가 덜 된 부분도 많고 코드 스타일도 이번에는 신경쓰지 못했어요😅
리뷰 잘 부탁드립니다ㅎㅎ
=> [Tomcat 구현하기 1 - 2단계] 페드로(류형욱) 미션 제출합니다.

study/build.gradle, study/src/main/java/cache/com/example/GreetingController.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, study/src/test/java/study/FileTest.java, study/src/test/java/study/IOStreamTest.java, tomcat/src/main/java/org/apache/catalina/Manager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/Session.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequestParser.java, tomcat/src/main/resources/static/login.html, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java
안녕하세요 레모네 🍋
바쁜 일주일이 벌써 지나갔네요
사전에 말씀드린대로 1단계와 2단계 완료하였습니다!
다만 기한을 맞추느라 보강하지 못한 부분이 있어서 해당 부분은 보충 예정입니다 🥲
- 2단계의 4번 부분에서 Session 관련 기능은 구현하였으나 쿠키 조회 부분에서의 문제가 있어 수정 예정입니다
- 학습 테스트의 경우, 완료하였으나 진행 후 커밋 되돌리기를 실행하고 미션을 진행하여서 다시 진행 예정입니다
해당 부분은 주말 내에 끝낼 예정입니다
제가 끝내기 전에 미리 리뷰 남겨 주셔도 괜찮아요👍
좋은 하루 보내세요 🎡
=> [1 -2단계 - Tomcat 구현하기] 시소(신지송) 미션 제출합니다

study/src/main/resources/application.yml, tomcat/src/main/java/com/techcourse/controller/AbstractController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/httpresponse/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/session/Session.java
안녕하세요 이상!
4단계 구현 완료하고 리뷰 요청 보냅니다~
저번에 3,4단계 한번에 내고 다시 롤백하고 보냈을때 4단계 학습테스트 일부를 롤백을 깜빡해서 file changed에 없는 테스트도 있습니다!
=> [4단계 - Tomcat 구현하기] 비토(오상훈) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java
안녕하세요 이상!
revert를 이용하는 방법을 몰라서 해당 pr을 close하고 새로 브랜치 파서 올립니다!
=> [4단계 - Tomcat 구현하기] 비토(오상훈) 미션 제출합니다

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage0/ThreadTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/session/SessionManager.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/support/TestHttpUtils.java
냥인🐈🧍‍♀️ 안녕하세요!
이번 미션은 학습할 내용이 대부분이어서 코드보단 PR 내용에 집중하였습니다.
그간 리뷰 덕에 정말 많이 배웠네요 😀
마지막 리뷰도 잘 부탁 드립니다! 🤗
테스트 코드 시작 시 아래 `newFixedThreadPool` 함수를 통해 2개의 스레드를 항상 유지하며 일을 처리하는 스레드풀을 생성합니다.
``` java
final var executor = (ThreadPoolExecutor) Executors.newFixedThreadPool(2);
```
이후 아래 코드를 통해 3번의 `logWithSleep()` 메서드를 실행합니다.
`logWithSleep()` 는 실행되면 1초를 기다린 후 입력으로 들어온 문자열을 `Logger` 로 출력하는 메서드입니다.
``` java
executor.submit(logWithSleep("hello fixed thread pools"));
executor.submit(logWithSleep("hello fixed thread pools"));
executor.submit(logWithSleep("hello fixed thread pools"));
```
학습 테스트의 목적은 위와 같이 3개의 일을 2개의 스레드가 있는 풀에 요청했을 때 `executor.getPoolSize()` 값과 `executor.getQueue().size()` 값이 얼마인지 인지하는 것입니다.
`executor.getPoolSize()` 는 스레드 풀에 현재 존재하는 워커 스레드의 개수를 의미하며 항상 2개를 유지하도록 생성하였으니 `2`가 될 것입니다. …
=> [4단계 - Tomcat 구현하기] 새양(양경호) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/test/java/org/apache/catalina/connector/ConnectorTest.java, tomcat/src/test/java/org/apache/catalina/connector/TestClient.java
허허... 브랜치 꼬인 걸 해결하다가 PR 작성했던 브랜치를 삭제해 버려서 PR이 닫혀버렸네요..
다시 요청 드립니다😅
---
이번 단계 진행 중 생긴 의문들을 정리해서 슬랙에 공유했었는데, 기록 차 PR 본문에도 남겨 둡니다ㅎㅎ
재즈도 아까 저랑 같이 고민했었으니 혹시 알게 된 것이 있다면 공유해 주세요🔥
(아래는 원문입니다.)
톰캣 4단계 미션 진행 중 궁금한 사항이 생겨 질문 남깁니다.
1. ServerSocket은 accept() 후 클라이언트와 연결이 수립된 Socket 객체를 반환합니다. 이 인스턴스 역시 AutoClosable인데 Http11Processor.process() 의 try with resource 구문에 빠져 있는 이유가 뭘까요? 소켓을 닫아주지 않아도 되는 걸까요?
2. POSIX 소켓은 socket() -> bind() -> listen() -> accept() -> [ 통신 ] -> close() 의 플로우를 가집니다.
클라이언트의 connect() 요청 시(SYN) 서버는 STN+ACK를 응답, 3-way handshaking 과정을 거치면서 서버-클라이언트 측 소켓이 ESTABLISHED 상태가 됩니다.
이때, 서버가 다른 요청을 처리하느라 바빠 ESTABLISHED 상태에 놓인 소켓을 accept() 해 주지 못한다면, 해당 요청들은 Accept큐(Backlog)에 남아 대기합니다.
ServerSocket의 생성자 두 번째 인자로 이 Accept 큐의 크기를 전달하여 소켓을 생성할 수 있는데요, 지정하지 않는다면 기본값으로 50이 사용됩니다. (리눅스 표준은 4096으로 …
=> [톰캣 구현하기 - 4단계] 페드로(류형욱) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/ConcurrencyTest.java, study/src/test/java/thread/stage1/UserServlet.java, study/src/test/java/thread/stage2/AppTest.java, tomcat/src/main/java/com/techcourse/controller/AbstractController.java, tomcat/src/main/java/com/techcourse/controller/IndexController.java, tomcat/src/main/java/com/techcourse/controller/LoginController.java, tomcat/src/main/java/com/techcourse/controller/RegisterController.java, tomcat/src/main/java/com/techcourse/controller/StaticResourceController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/RequestDispatcher.java, tomcat/src/main/java/org/apache/coyote/http11/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/cookie/Cookie.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java, tomcat/src/test/java/org/apache/coyote/http11/Http11ProcessorTest.java, tomcat/src/test/java/org/apache/coyote/http11/request/HttpRequestTest.java, tomcat/src/test/java/org/apache/coyote/http11/response/HttpResponseTest.java
안녕하세요, 클로버! 🍀
리브입니다. 😊
4단계 완료하여 PR 드립니다.
LMS에 적혀있는 바와 같이 학습 테스트를 꼼꼼히 하면서 스레드 풀 동작 원리를 이해하는 것에 집중 했습니다. 😊
그리고 3단계 리뷰 주신 내용도 같이 반영 완료 했습니다.
리뷰 하다가 궁금한 내용 있으시면 편하게 DM 주세요! 👍
> [의견]
개인적으로 메서드명만 봤을 땐 로그인 여부를 확인해줄 것 같은데 내부에서 setRedirect()까지 해준다고 예측하기 힘들 것 같아요.
하지만 다른 객체의 메서드가 아니라 본인의 메서드를 호출하는거라 내부 구현을 알고 있는 상황이니 지금도 괜찮을 것 같습니다.
타당한 의견이라고 생각되신다면 수용해주시고 아니면 그대로 구현해주셔도 좋습니다! 😄
[`3bcb2bb`](https://github.com/Minjoo522/java-http/commit/3bcb2bbe5be91bfef2efa43bb23b64c4305368f7)
`isLoggedIn` 메서드가 로그인 여부만 확인하고 리다이렉트는 `doGet`에서 하도록 개선 했습니다.
---
> [의견] 만약 `orElse(null)`을 사용한다면, `ifPresentOrElse()`를 활용해볼 수 있을 것 같기도 하네요! 이것도 리브의 취향에 따라 반영 여부 결정해주세요 😄
`ifPresentOrElse()`를 사용하게 되면 아래처럼 try-catch로 감싸주는 과정이 필요해서 오히려 코드가 복잡해 보일 것 같습니다. 😭
물론 내부 로직을 다른 메서드로 추출할 수도 있지만 재사용되는 로직이 아니기 때문에 `User`를 리턴하고 null 값을 체크하는 …
=> [4단계- Tomcat 구현하기] 리브(김민주) 미션 제출합니다.

study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, tomcat/src/main/java/com/techcourse/controller/RootController.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/catalina/startup/Tomcat.java, tomcat/src/main/java/org/apache/coyote/AbstractController.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/body/ResponseBody.java, tomcat/src/main/java/org/apache/coyote/http11/response/header/ResponseHeaders.java, tomcat/src/test/java/org/apache/coyote/http11/response/HttpResponseTest.java, tomcat/src/test/java/org/apache/coyote/http11/response/body/ResponseBodyTest.java
낙낙 안녕하세요~ 😀
시간이 정말 빠르네요 벌써 마지막 4단계 리뷰 요청이라니.. ㅠㅠ
이번 마지막 미션은 스레드 풀을 생성해서 매 요청마다 스레드를 무제한 생성하지 않도록 제한을 두고
동시성을 고려하여 동기화 컬렉션을 사용하는 것이 목표였어요.
기능 요구 사항이 복잡하지는 않았기에 구현은 간단하게 끝났었는데요
오늘 하루 종일 다 같이 삽질한 ㅋㅋ 스레드 풀과 acceptCount, Socket accept 에 관한 내용은 아직도 의문으로 남아있어요.
현재는 새로운 클라이언트 요청이 들어오는 시점마다 소켓의 `listen()` 함수 호출 후 백로그를 거치지 않고 바로 `accept()`가 호출되어 스레드 풀로 `submit` 되고 있는데요. 스레드 풀의 대기 큐 크기 초과 정책으로 추가 요청을 거절한다고 해도, accept() 호출 시점이 고려되지 않기 때문에 요청이 단시간에 폭발했을 시에 심각한 메모리 낭비를 유발할 것 같다는 생각이 들어요.
유휴 스레드가 생겨서 백로그로부터 사용자 요청을 처리하는 시점에 `accept()`를 처리 하도록 하는게 더 나은 방안일 것 같기도한데 아직은 정확하게 근거를 못찾겠네요. 어플리케이션의 스레드 풀이 OS 소켓 자원을 일방적으로 조절하는 방식이 가장 나은 대안인지도 의문이 들어요. 두 레벨간의 적절한 조화를 찾는 방법이 있을 것 같은데 지금 학습 단계에서는 아직까지는 어렵네요. 😅
낙낙도 여전히 같은 생각이신지 궁금하고, 혹시나 새롭게 알게된 지식이 있다면 알려주세요ㅎㅎ
마지막 리뷰도 잘 부탁드립니다 낙낙 
즐거운 추석 연휴 보내세요 !! 😁
=> [4단계 - Tomcat 구현하기] 재즈(함석명) 미션 제출합니다.

study/src/main/java/cache/com/example/cachecontrol/CacheControlInterceptor.java, study/src/main/java/cache/com/example/cachecontrol/CacheWebConfig.java, study/src/main/java/cache/com/example/etag/EtagFilterConfiguration.java, study/src/main/java/cache/com/example/version/CacheBustingWebConfig.java, study/src/main/resources/application.yml, study/src/test/java/thread/stage0/SynchronizationTest.java, study/src/test/java/thread/stage0/ThreadPoolsTest.java, study/src/test/java/thread/stage1/UserServlet.java, tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/RequestMapping.java, tomcat/src/main/java/org/apache/coyote/http11/Http11Processor.java, tomcat/src/main/java/org/apache/coyote/http11/HttpReader.java, tomcat/src/main/java/org/apache/coyote/http11/request/HttpRequest.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestBody.java, tomcat/src/main/java/org/apache/coyote/http11/request/RequestLine.java, tomcat/src/main/java/org/apache/coyote/http11/response/ContentType.java, tomcat/src/main/java/org/apache/coyote/http11/response/HttpResponse.java, tomcat/src/main/java/org/apache/coyote/http11/response/Status.java, tomcat/src/main/java/org/apache/coyote/http11/response/StatusLine.java, tomcat/src/main/java/org/apache/coyote/http11/session/SessionManager.java
=> [톰캣 구현하기 4단계] 호기(조호연) 미션 제출합니다.

tomcat/src/main/java/org/apache/catalina/connector/Connector.java, tomcat/src/main/java/org/apache/coyote/http11/SessionManager.java
안녕하세요 잉크~
4단계 미션 제출합니다~
학습테스트 커밋이 이전 pr에 있어서 해당 pr에서 다시 확인해주셔도 좋을 것 같아요!
[Thread 학습테스트](https://github.com/woowacourse/java-http/pull/610/commits/8dc2b1293e157fcb079b48efd14bfe8bd731a9e3)
=> [4단계 - Tomcat 구현하기] 카피(김상혁) 미션 제출합니다.

study/build.gradle, study/src/main/java/cache/com/example/version/HandlebarsConfig.java, study/src/main/java/cache/com/example/version/VersionHandlebarsHelper.java
현재 템플릿 엔진으로 사용되는 `handlebars-spring-boot-starter`는 springboot3을 지원하지 않습니다. 
`/resources/templates` 내의 템플릿을 정상적으로 로드하지 못하고, `resource-versioning.html` 내에서 `{{staticUrls}}`를 제대로 랜더링하지 못합니다.
이에 Springboot 3을 지원하는 `handlebars-springmvc` 으로 템플릿 엔진을 변경합니다.
- 종속성을 `handlebars-springmvc` 로 변경
- 커스텀 `HandlebarsHelper` 등록 방법 변경에 따른 수정
- 더 이상 사용되지 않는 `application.yml`의 `handlebars.suffix` 설정 제거
---
- 레퍼런스: https://github.com/allegro/handlebars-spring-boot-starter/issues/46
=> fix: replace handlebars template engine deps
